services:

  postgres:
    image: postgis/postgis:17-3.5
    container_name: CartaVault
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-poi_manager}
      POSTGRES_USER: ${POSTGRES_USER:-poi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be defined}

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
volumes:
  postgres_data: