import { useEffect, useRef, useState, type FormEvent } from 'react'
import { createPortal } from 'react-dom'
import { AlertTriangle, MonitorSmartphone, Settings2, Shield, ShieldCheck, Trash2, Upload, UserRound, X } from 'lucide-react'

import { accountAvatarUrl, changeAccountEmail, changeAccountPassword, deleteAccountAvatar, deleteOwnAccount, getAccountProfile, getAccountSessions, revokeAccountSession, revokeOtherAccountSessions, updateAccountProfile, uploadAccountAvatar } from '../../api/account'
import { SESSION_EXPIRED_EVENT } from '../../api/client'
import { useAuth } from '../../auth/useAuth'
import type { AccountProfile, AccountSession } from '../../types/account'

type Section = 'profile' | 'security' | 'sessions' | 'preferences' | 'admin' | 'danger'

export function AccountModal({ onClose, onOpenAdmin, trigger }: { onClose: () => void; onOpenAdmin: () => void; trigger: HTMLElement | null }) {
  const { user, refresh } = useAuth()
  const [section, setSection] = useState<Section>('profile')
  const [profile, setProfile] = useState<AccountProfile | null>(null)
  const [sessions, setSessions] = useState<AccountSession[]>([])
  const [error, setError] = useState<string | null>(null)
  const [message, setMessage] = useState<string | null>(null)
  const closeButton = useRef<HTMLButtonElement>(null)
  const load = async () => { setProfile(await getAccountProfile()); setSessions(await getAccountSessions()) }
  useEffect(() => { void load().catch((e: unknown) => setError(e instanceof Error ? e.message : 'Chargement impossible.')) }, [])
  useEffect(() => {
    const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; closeButton.current?.focus()
    const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }
    window.addEventListener('keydown', escape)
    return () => { document.body.style.overflow = previous; window.removeEventListener('keydown', escape); trigger?.focus() }
  }, [onClose, trigger])
  const run = async (action: () => Promise<void>, success: string) => { setError(null); setMessage(null); try { await action(); setMessage(success) } catch (e) { setError(e instanceof Error ? e.message : 'Opération impossible.') } }
  const avatar = accountAvatarUrl(profile?.avatar_url ?? user?.avatar_url ?? null)
  const initials = (profile?.display_name ?? user?.display_name ?? '?').trim().charAt(0).toUpperCase()
  const submit = (handler: (data: FormData) => Promise<void>) => (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void handler(new FormData(event.currentTarget)) }

  return createPortal(<div className="account-overlay" role="presentation"><section className="account-modal" role="dialog" aria-modal="true" aria-labelledby="account-title">
    <header className="account-modal__header"><div className="account-avatar">{avatar ? <img src={avatar} alt={`Avatar de ${profile?.display_name ?? user?.display_name}`} /> : initials}</div><div><h2 id="account-title">{profile?.display_name ?? user?.display_name}</h2><p>{profile?.email ?? user?.email}</p>{user?.is_admin && <span><Shield size={13} />Administrateur</span>}</div><button ref={closeButton} className="panel-icon-button" type="button" aria-label="Fermer l’espace compte" onClick={onClose}><X size={18} /></button></header>
    <nav className="account-modal__nav" aria-label="Gestion du compte">{([['profile', UserRound, 'Mon profil'], ['security', ShieldCheck, 'Sécurité'], ['sessions', MonitorSmartphone, 'Sessions actives'], ['preferences', Settings2, 'Préférences']] as const).map(([id, Icon, label]) => <button key={id} type="button" aria-current={section === id ? 'page' : undefined} onClick={() => setSection(id)}><Icon size={17} />{label}</button>)}{user?.is_admin && <button type="button" onClick={() => setSection('admin')} aria-current={section === 'admin' ? 'page' : undefined}><Shield size={17} />Administration</button>}<button className="danger" type="button" onClick={() => setSection('danger')} aria-current={section === 'danger' ? 'page' : undefined}><AlertTriangle size={17} />Zone sensible</button></nav>
    <main className="account-modal__content">{error && <div className="form-alert" role="alert">{error}</div>}{message && <div className="account-success" role="status">{message}</div>}
      {section === 'profile' && profile && <><AccountHeading title="Mon profil" description="Gérez votre identité et votre avatar CartaVault." /><div className="account-avatar-editor"><div className="account-avatar large">{avatar ? <img src={avatar} alt="Aperçu de l’avatar" /> : initials}</div><div><label className="account-button account-button--secondary"><Upload size={15} />Modifier l’avatar<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) void run(async () => { await uploadAccountAvatar(file); await refresh(); await load() }, 'Avatar mis à jour.') }} /></label>{avatar && <button className="account-button account-button--danger-quiet" type="button" onClick={() => void run(async () => { await deleteAccountAvatar(); await refresh(); await load() }, 'Avatar supprimé.')}><Trash2 size={15} />Supprimer</button>}<small>JPEG, PNG ou WebP · 5 Mio maximum.</small></div></div><form className="account-form" onSubmit={submit(async (data) => run(async () => { await updateAccountProfile(String(data.get('display_name'))); await refresh(); await load() }, 'Profil mis à jour.'))}><label>Nom d’affichage<input name="display_name" defaultValue={profile.display_name} required maxLength={120} /></label><button className="account-button account-button--primary" type="submit">Enregistrer</button></form><dl className="account-metadata"><dt>Adresse e-mail</dt><dd>{profile.email}</dd><dt>Compte créé</dt><dd>{new Date(profile.created_at).toLocaleDateString('fr-FR')}</dd><dt>Dernière connexion</dt><dd>{profile.last_login_at ? new Date(profile.last_login_at).toLocaleString('fr-FR') : 'Non disponible'}</dd></dl></>}
      {section === 'security' && profile && <><AccountHeading title="Sécurité" description="Les autres appareils seront déconnectés après une modification sensible." /><form className="account-form" onSubmit={submit(async (data) => run(async () => { await changeAccountEmail(String(data.get('current_password')), String(data.get('new_email'))); await refresh(); await load() }, 'Adresse e-mail mise à jour.'))}><h3>Changer l’adresse e-mail</h3><label>Nouvelle adresse<input name="new_email" type="email" required /></label><label>Mot de passe actuel<input name="current_password" type="password" required /></label><button className="account-button account-button--primary" type="submit">Modifier l’e-mail</button></form><form className="account-form" onSubmit={submit(async (data) => run(() => changeAccountPassword(String(data.get('current_password')), String(data.get('new_password')), String(data.get('confirmation'))), 'Mot de passe mis à jour.'))}><h3>Changer le mot de passe</h3><label>Mot de passe actuel<input name="current_password" type="password" required /></label><label>Nouveau mot de passe<input name="new_password" type="password" minLength={12} required /></label><label>Confirmation<input name="confirmation" type="password" minLength={12} required /></label><button className="account-button account-button--primary" type="submit">Modifier le mot de passe</button></form><div className="account-info"><strong>{profile.active_session_count}</strong> sessions actives · Compte {profile.is_active ? 'actif' : 'inactif'}. L’authentification à deux facteurs n’est pas encore disponible.</div></>}
      {section === 'sessions' && <><AccountHeading title="Sessions actives" description="Contrôlez les appareils connectés à votre compte." /><button className="account-button account-button--secondary" type="button" onClick={() => void run(async () => { await revokeOtherAccountSessions(); await load() }, 'Autres sessions révoquées.')}>Révoquer les autres sessions</button><ul className="account-sessions">{sessions.map((item) => <li key={item.id}><MonitorSmartphone size={19} /><div><strong>{item.user_agent || 'Appareil inconnu'}</strong><span>Dernière activité : {new Date(item.last_used_at).toLocaleString('fr-FR')}</span>{item.is_current && <b>Session actuelle</b>}</div><button className="panel-icon-button danger" type="button" aria-label="Révoquer cette session" onClick={() => void run(async () => { await revokeAccountSession(item.id); if (item.is_current) window.dispatchEvent(new Event(SESSION_EXPIRED_EVENT)); else await load() }, 'Session révoquée.')}><Trash2 size={15} /></button></li>)}</ul></>}
      {section === 'preferences' && <Preferences />}
      {section === 'admin' && <><AccountHeading title="Administration" description="La gestion globale des utilisateurs reste séparée de votre compte personnel." /><button className="account-button account-button--primary" type="button" onClick={() => { onClose(); onOpenAdmin() }}>Ouvrir l’administration</button></>}
      {section === 'danger' && profile && <><AccountHeading title="Zone sensible" description="La suppression désactive et anonymise définitivement votre compte." /><div className="account-danger-summary"><p>{profile.owned_maps.length} carte(s) possédée(s), {profile.shared_map_count} carte(s) partagée(s).</p>{profile.owned_maps.length > 0 && <><strong>Transférez ou supprimez d’abord :</strong><ul>{profile.owned_maps.map((map) => <li key={map.id}>{map.name}</li>)}</ul></>}</div><form className="account-form danger" onSubmit={submit(async (data) => run(async () => { await deleteOwnAccount(String(data.get('current_password')), String(data.get('confirmation')), data.get('acknowledged') === 'on'); window.dispatchEvent(new Event(SESSION_EXPIRED_EVENT)) }, 'Compte supprimé.'))}><label>Mot de passe actuel<input name="current_password" type="password" required /></label><label>Confirmation<input name="confirmation" placeholder="SUPPRIMER MON COMPTE" required /></label><label className="checkbox-field"><input name="acknowledged" type="checkbox" required />Je comprends que cette action est définitive.</label><button className="account-button account-button--danger" type="submit" disabled={!profile.can_delete}>Supprimer mon compte</button></form></>}
    </main>
  </section></div>, document.body)
}

function AccountHeading({ title, description }: { title: string; description: string }) { return <header className="account-content-heading"><p className="cv-workspace-panel__eyebrow">Compte</p><h2>{title}</h2><span>{description}</span></header> }
function Preferences() { const [density, setDensity] = useState(() => localStorage.getItem('cartavault.density') ?? 'comfortable'); return <><AccountHeading title="Préférences" description="Réglages conservés uniquement dans ce navigateur." /><div className="account-form"><label>Densité d’affichage<select value={density} onChange={(e) => { setDensity(e.target.value); localStorage.setItem('cartavault.density', e.target.value) }}><option value="comfortable">Confortable</option><option value="compact">Compacte</option></select></label><label>Langue<select disabled><option>Français</option></select></label><label>Fuseau horaire<input readOnly value={Intl.DateTimeFormat().resolvedOptions().timeZone} /></label><button className="account-button account-button--secondary" type="button" onClick={() => { localStorage.removeItem('cartavault.density'); localStorage.removeItem('cartavault.basemap'); setDensity('comfortable') }}>Réinitialiser les préférences</button></div></> }
