import { useState, type FormEvent } from 'react'
import { Eye, EyeOff, KeyRound, RefreshCw, Trash2 } from 'lucide-react'

import { deleteGooglePlacesCredential, storeGooglePlacesCredential, verifyGooglePlacesCredential } from '../../api/account'
import type { GooglePlacesCredentialStatus } from '../../types/account'
import { FieldHelp } from '../common/FieldHelp'
import { useConfirmDialog } from '../common/useConfirmDialog'
import { formatCredentialDate } from './credentialDate'

export function GooglePlacesCredentialPanel({ status, storageAvailable, onChanged }: { status: GooglePlacesCredentialStatus; storageAvailable: boolean; onChanged: (status: GooglePlacesCredentialStatus, providerReset?: boolean) => Promise<void> | void }) {
  const { confirm, confirmationDialog } = useConfirmDialog()
  const [editing, setEditing] = useState(false); const [revealed, setRevealed] = useState(false); const [apiKey, setApiKey] = useState(''); const [deletePassword, setDeletePassword] = useState(''); const [confirmingDelete, setConfirmingDelete] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null)
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(null); setMessage(null); try { const next = await storeGooglePlacesCredential(apiKey); setApiKey(''); setEditing(false); setRevealed(false); await onChanged(next); setMessage('Clé enregistrée. Vérifiez-la avant de sélectionner Google Places.') } catch (reason) { setApiKey(''); setError(reason instanceof Error ? reason.message : 'Impossible d’enregistrer la clé.') } finally { setBusy(false) } }
  const verify = async () => { setBusy(true); setError(null); setMessage(null); try { const next = await verifyGooglePlacesCredential(); await onChanged(next); setMessage('La clé Google Places est valide.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'La vérification a échoué.') } finally { setBusy(false) } }
  const remove = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!await confirm({ title: 'Supprimer la clé Google Places ?', message: 'Les lieux existants seront conservés. Les prochaines recherches utiliseront Stadia.' })) return; setBusy(true); setError(null); try { const result = await deleteGooglePlacesCredential(deletePassword); setDeletePassword(''); setConfirmingDelete(false); await onChanged({ configured: false, last4: null, verified: false, verified_at: null, last_used_at: null, last_error_code: null }, result.provider_reset); setMessage('Clé supprimée. La recherche utilise Stadia.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Impossible de supprimer la clé.') } finally { setBusy(false) } }
  return <section className="account-credential" aria-labelledby="google-places-credential-title">
    <div className="account-credential__heading"><span className="account-credential__icon"><KeyRound size={18} aria-hidden="true" /></span><div><h3 id="google-places-credential-title">Clé Google Places<FieldHelp>La clé est chiffrée sur le serveur et doit autoriser Places API (New).</FieldHelp></h3><p>{status.configured ? <>Clé configurée <strong>••••••••{status.last4}</strong></> : 'Aucune clé configurée'}</p></div>{status.configured && status.verified && <span className="account-credential__verification"><span className="account-credential__status">Vérifiée</span>{status.verified_at && <time dateTime={status.verified_at}>{formatCredentialDate(status.verified_at)}</time>}</span>}</div>
    {!storageAvailable && <p className="account-credential__warning">Le stockage sécurisé des clés utilisateur n’est pas configuré.</p>}
    {status.last_error_code && <p className="account-credential__warning">La clé doit autoriser Google Places API (New).</p>}
    {(editing || !status.configured) && storageAvailable && <form className="account-credential__form" onSubmit={submit}><label>Nouvelle clé<span className="account-secret-input"><input aria-label="Clé Google Places" type={revealed ? 'text' : 'password'} value={apiKey} required maxLength={512} autoComplete="off" onChange={(event) => setApiKey(event.target.value)} /><button type="button" aria-label={revealed ? 'Masquer la clé' : 'Afficher la clé'} onClick={() => setRevealed((value) => !value)}>{revealed ? <EyeOff size={16} /> : <Eye size={16} />}</button></span></label><div className="account-credential__actions"><button className="account-button account-button--primary" type="submit" disabled={busy}>Enregistrer cette clé</button>{status.configured && <button className="account-button account-button--secondary" type="button" onClick={() => setEditing(false)}>Annuler</button>}</div></form>}
    {status.configured && !editing && <div className="account-credential__actions"><button className="account-button account-button--secondary" type="button" disabled={busy} onClick={() => setEditing(true)}>Remplacer</button><button className="account-button account-button--secondary" type="button" disabled={busy} onClick={() => void verify()}><RefreshCw size={15} />Vérifier</button><button className="account-button account-button--secondary account-button--danger-hover" type="button" disabled={busy} onClick={() => setConfirmingDelete((value) => !value)}><Trash2 size={15} />Supprimer</button></div>}
    {confirmingDelete && <form className="account-credential__delete" onSubmit={remove}><label>Mot de passe actuel<input type="password" value={deletePassword} required onChange={(event) => setDeletePassword(event.target.value)} /></label><button className="account-button account-button--danger" type="submit">Confirmer la suppression</button></form>}
    {error && <div className="form-alert" role="alert">{error}</div>}{message && <div className="account-success" role="status">{message}</div>}{confirmationDialog}
  </section>
}
