import { useState, type FormEvent } from 'react'
import { Eye, EyeOff, KeyRound, RefreshCw, Trash2 } from 'lucide-react'

import { deleteOpenRouteServiceCredential, storeOpenRouteServiceCredential, verifyOpenRouteServiceCredential } from '../../api/account'
import type { OpenRouteServiceCredentialStatus } from '../../types/account'
import { FieldHelp } from '../common/FieldHelp'
import { useConfirmDialog } from '../common/useConfirmDialog'
import { formatCredentialDate } from './credentialDate'

export function OpenRouteServiceCredentialPanel({ status, storageAvailable, onChanged }: { status: OpenRouteServiceCredentialStatus; storageAvailable: boolean; onChanged: (status: OpenRouteServiceCredentialStatus, providerReset?: boolean) => Promise<void> | void }) {
  const { confirm, confirmationDialog } = useConfirmDialog()
  const [editing, setEditing] = useState(false); const [revealed, setRevealed] = useState(false)
  const [apiKey, setApiKey] = useState(''); const [deletePassword, setDeletePassword] = useState('')
  const [confirmingDelete, setConfirmingDelete] = useState(false); const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null)
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { const next = await storeOpenRouteServiceCredential(apiKey); setApiKey(''); setEditing(false); await onChanged(next); setMessage('Clé enregistrée. Vérifiez-la avant utilisation.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Impossible d’enregistrer la clé.') } finally { setBusy(false) } }
  const verify = async () => { setBusy(true); setError(null); try { const next = await verifyOpenRouteServiceCredential(); await onChanged(next); setMessage('La clé OpenRouteService est valide.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'La vérification a échoué.') } finally { setBusy(false) } }
  const remove = async (event: FormEvent) => { event.preventDefault(); if (!await confirm({ title: 'Supprimer la clé OpenRouteService ?', message: 'Les prochains calculs utiliseront OSRM, sauf si un serveur ORS sans clé est configuré.' })) return; setBusy(true); setError(null); try { const result = await deleteOpenRouteServiceCredential(deletePassword); setDeletePassword(''); setConfirmingDelete(false); await onChanged({ configured: false, last4: null, verified: false, verified_at: null, last_used_at: null, last_error_code: null, self_hosted: status.self_hosted }, result.provider_reset); setMessage('Clé supprimée.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Impossible de supprimer la clé.') } finally { setBusy(false) } }
  if (status.self_hosted && !status.configured) return <div className="account-success" role="status">Serveur OpenRouteService auto-hébergé actif : aucune clé personnelle n’est requise.</div>
  return <section className="account-credential" aria-labelledby="ors-credential-title">
    <div className="account-credential__heading"><span className="account-credential__icon"><KeyRound size={18} /></span><div><h3 id="ors-credential-title">Clé OpenRouteService<FieldHelp>Chiffrée côté serveur, déchiffrée uniquement au moment du calcul et jamais renvoyée au navigateur.</FieldHelp></h3><p>{status.configured ? <>Clé configurée <strong>••••••••{status.last4}</strong></> : 'Aucune clé configurée'}</p></div>{status.configured && status.verified && <span className="account-credential__verification"><span className="account-credential__status">Vérifiée</span>{status.verified_at && <time dateTime={status.verified_at}>{formatCredentialDate(status.verified_at)}</time>}</span>}</div>
    {!storageAvailable && <p className="account-credential__warning">Le stockage sécurisé des clés n’est pas configuré.</p>}
    {status.last_error_code && <p className="account-credential__warning">Dernière erreur : {status.last_error_code}</p>}
    {(editing || !status.configured) && storageAvailable && <form className="account-credential__form" onSubmit={submit}><label>Nouvelle clé<span className="account-secret-input"><input aria-label="Clé OpenRouteService" type={revealed ? 'text' : 'password'} value={apiKey} required maxLength={512} autoComplete="off" onChange={(event) => setApiKey(event.target.value)} /><button type="button" aria-label={revealed ? 'Masquer la clé' : 'Afficher la clé'} onClick={() => setRevealed(!revealed)}>{revealed ? <EyeOff size={16} /> : <Eye size={16} />}</button></span></label><div className="account-credential__actions"><button className="account-button account-button--primary" disabled={busy}>Enregistrer cette clé</button>{status.configured && <button className="account-button account-button--secondary" type="button" onClick={() => setEditing(false)}>Annuler</button>}</div></form>}
    {status.configured && !editing && <div className="account-credential__actions"><button className="account-button account-button--secondary" type="button" onClick={() => setEditing(true)}>Remplacer</button><button className="account-button account-button--secondary" type="button" disabled={busy} onClick={() => void verify()}><RefreshCw size={15} />Vérifier</button><button className="account-button account-button--secondary account-button--danger-hover" type="button" onClick={() => setConfirmingDelete(!confirmingDelete)}><Trash2 size={15} />Supprimer</button></div>}
    {confirmingDelete && <form className="account-credential__delete" onSubmit={remove}><label>Mot de passe actuel<input type="password" value={deletePassword} required autoComplete="current-password" onChange={(event) => setDeletePassword(event.target.value)} /></label><button className="account-button account-button--danger" disabled={busy}>Confirmer la suppression</button></form>}
    {error && <div className="form-alert" role="alert">{error}</div>}{message && <div className="account-success" role="status">{message}</div>}{confirmationDialog}
  </section>
}
