import { useEffect, useMemo, useState } from 'react'
import { createPortal } from 'react-dom'
import { CalendarDays, Check, Eye, EyeOff, Info, KeyRound, Pencil, Play, Plus, Save, ShieldCheck, Trash2, TriangleAlert, X } from 'lucide-react'

import { createPersonalApiKey, deletePersonalApiKey, getPersonalApiKeys, updatePersonalApiKey, verifyPersonalApiKey } from '../../api/account'
import type { PersonalApiKey } from '../../types/account'
import { useConfirmDialog } from '../common/useConfirmDialog'

export function PersonalApiKeysSection() {
  const [keys, setKeys] = useState<PersonalApiKey[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [editing, setEditing] = useState<PersonalApiKey | null | 'new'>(null)
  const [name, setName] = useState('')
  const [provider, setProvider] = useState<'google' | 'stadia' | 'openrouteservice'>('google')
  const [secret, setSecret] = useState('')
  const [showSecret, setShowSecret] = useState(false)
  const [busy, setBusy] = useState(false)
  const [detailsKey, setDetailsKey] = useState<PersonalApiKey | null>(null)
  const { confirm, confirmationDialog } = useConfirmDialog()
  const load = () => void getPersonalApiKeys().then(setKeys).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Impossible de charger les clés API.')).finally(() => setLoading(false))
  useEffect(load, [])
  const metrics = useMemo(() => ({ configured: keys.length, verified: keys.filter((key) => key.verified).length, errors: keys.filter((key) => key.last_error_code).length, lastActivity: keys.map((key) => key.last_used_at ?? key.verified_at).filter((value): value is string => Boolean(value)).sort().at(-1) ?? null }), [keys])
  const open = (key: PersonalApiKey | 'new') => { setEditing(key); setName(key === 'new' ? '' : key.name); setProvider(key === 'new' ? 'google' : key.provider); setSecret(''); setShowSecret(false); setError(null) }
  const save = async () => { if (!editing || !name.trim() || (editing === 'new' && !secret.trim())) return; setBusy(true); setError(null); try { const key = editing === 'new' ? await createPersonalApiKey({ name: name.trim(), provider, api_key: secret.trim() }) : await updatePersonalApiKey(editing.id, { name: name.trim(), ...(secret.trim() ? { api_key: secret.trim() } : {}) }); setKeys((items) => editing === 'new' ? [...items, key] : items.map((item) => item.id === key.id ? key : item)); setEditing(null) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Enregistrement impossible.') } finally { setBusy(false) } }
  const saveAndTest = async () => { if (!editing || !name.trim() || (editing === 'new' && !secret.trim())) return; setBusy(true); setError(null); try { const key = editing === 'new' ? await createPersonalApiKey({ name: name.trim(), provider, api_key: secret.trim() }) : await updatePersonalApiKey(editing.id, { name: name.trim(), ...(secret.trim() ? { api_key: secret.trim() } : {}) }); setKeys((items) => editing === 'new' ? [...items, key] : items.map((item) => item.id === key.id ? key : item)); setEditing(key); setSecret(''); try { const verified = await verifyPersonalApiKey(key.id); setKeys((items) => items.map((item) => item.id === key.id ? verified : item)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Le test a échoué. La clé reste enregistrée.'); load() } } catch (reason) { setError(reason instanceof Error ? reason.message : 'Enregistrement impossible.') } finally { setBusy(false) } }
  const test = async (key: PersonalApiKey) => { setBusy(true); setError(null); try { const next = await verifyPersonalApiKey(key.id); setKeys((items) => items.map((item) => item.id === key.id ? next : item)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Le test a échoué.'); load() } finally { setBusy(false) } }
  const remove = async (key: PersonalApiKey) => { if (!await confirm({ title: 'Supprimer cette clé API', message: `La clé « ${key.name} » ne pourra plus être utilisée par vos préférences.`, confirmLabel: 'Supprimer', variant: 'danger' })) return; setBusy(true); try { await deletePersonalApiKey(key.id); setKeys((items) => items.filter((item) => item.id !== key.id)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Suppression impossible.') } finally { setBusy(false) } }
  return <><header className="account-content-heading"><p className="cv-workspace-panel__eyebrow">Compte</p><h2>Clés API</h2><span>Ajoutez vos clés Google, Stadia ou ORS, puis choisissez leur utilisation dans vos préférences.</span></header>
    {error && <div className="form-alert" role="alert">{error}</div>}
    <section className="account-security-summary account-personal-api-summary" aria-label="Résumé des clés API"><div className="account-api-summary"><Metric icon={KeyRound} value={metrics.configured} label="Clés enregistrées" /><Metric icon={Check} value={metrics.verified} label="Vérifiées" /><Metric icon={TriangleAlert} value={metrics.errors} label="Erreurs" tone="warning" /><Metric icon={CalendarDays} value={metrics.lastActivity ? formatDate(metrics.lastActivity, false) : 'Jamais'} label="Dernière activité" /></div></section>
    <section className="account-preference-card account-api-catalog">
      <header className="account-api-catalog__header"><div><div className="account-preference-card__heading"><span className="account-preference-card__icon"><KeyRound size={19} aria-hidden="true" /></span><h3>Mes clés API</h3></div><p>Une même clé peut servir au routage, à la recherche de lieux et aux fonds de carte.</p></div><button className="account-button account-button--primary" type="button" onClick={() => open('new')}><Plus size={16} />Ajouter une clé</button></header>
      {loading ? <p className="account-card-description">Chargement…</p> : keys.length === 0 ? <p className="account-api-catalog__empty">Aucune clé personnelle ajoutée.</p> : <div className="account-api-catalog__cards">{keys.map((key) => <ApiKeyCard key={key.id} item={key} busy={busy} onTest={test} onEdit={open} onDelete={remove} onDetails={setDetailsKey} />)}</div>}
    </section><aside className="account-api-key-note"><Info size={22} /><p>Une même clé peut être utilisée pour le routage, la recherche de lieux ou les fonds de carte.<br />Assurez-vous qu’elle possède les droits nécessaires pour les services utilisés.</p></aside>
    {editing && createPortal(<div className="account-api-key-dialog-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setEditing(null) }}><section className="account-api-key-dialog" role="dialog" aria-modal="true" aria-label={editing === 'new' ? 'Nouvelle clé API' : 'Modifier la clé API'}><header><div><h3>{editing === 'new' ? 'Nouvelle clé API' : 'Modifier la clé API'}</h3><p>Renseignez les informations pour {editing === 'new' ? 'ajouter une nouvelle clé.' : 'mettre à jour cette clé.'}</p></div><button type="button" aria-label="Fermer" onClick={() => setEditing(null)}><X size={18} /></button></header>{error && <div className="form-alert" role="alert">{error}</div>}<div className="account-api-key-dialog__fields"><label>Nom de la clé<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex. Google personnel" autoFocus /></label>{editing === 'new' && <fieldset><legend>Type</legend><div className="account-api-key-provider-choice account-api-key-provider-choice--three"><button type="button" className={provider === 'google' ? 'is-selected' : ''} onClick={() => setProvider('google')}><img src="https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg" alt="" />Google</button><button type="button" className={provider === 'stadia' ? 'is-selected' : ''} onClick={() => setProvider('stadia')}><img src="https://www.stadiamaps.com/favicon.ico" alt="" />Stadia</button><button type="button" className={provider === 'openrouteservice' ? 'is-selected' : ''} onClick={() => setProvider('openrouteservice')}><img src="/brands/ors-logo.jpeg" alt="" />ORS</button></div></fieldset>}<label className="account-api-key-dialog__secret">{editing === 'new' ? 'Clé API' : 'Nouvelle clé API (optionnel)'}<span><input type={showSecret ? 'text' : 'password'} value={secret} onChange={(event) => setSecret(event.target.value)} placeholder="Saisissez votre clé API" autoComplete="off" /><button type="button" aria-label={showSecret ? 'Masquer la clé' : 'Afficher la clé'} onClick={() => setShowSecret((value) => !value)}>{showSecret ? <EyeOff size={17} /> : <Eye size={17} />}</button></span></label><aside><ShieldCheck size={19} /><p>Votre clé API est stockée de manière sécurisée et chiffrée. Elle ne sera jamais partagée ni visible après l’enregistrement.</p></aside></div><footer><button className="account-button account-button--secondary" type="button" onClick={() => setEditing(null)}>Annuler</button><button className="account-button account-button--secondary" type="button" disabled={busy || !name.trim() || (editing === 'new' && !secret.trim())} onClick={() => void saveAndTest()}><Play size={15} />Tester</button><button className="account-button account-button--primary" type="button" disabled={busy || !name.trim() || (editing === 'new' && !secret.trim())} onClick={() => void save()}><Save size={15} />Enregistrer</button></footer></section></div>, document.body)}
    {detailsKey && createPortal(<div className="account-api-key-dialog-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setDetailsKey(null) }}><section className="account-api-key-dialog account-api-key-error-dialog" role="dialog" aria-modal="true" aria-labelledby="api-key-error-title"><header><div><p>CLÉ API</p><h3 id="api-key-error-title">Détails de l’erreur</h3></div><button type="button" aria-label="Fermer" onClick={() => setDetailsKey(null)}><X size={18} /></button></header><div className="account-api-key-error-dialog__content"><TriangleAlert size={22} /><dl><dt>Clé</dt><dd>{detailsKey.name}</dd><dt>Fournisseur</dt><dd>{detailsKey.provider === 'google' ? 'Google' : detailsKey.provider === 'stadia' ? 'Stadia' : 'ORS'}</dd><dt>Statut HTTP</dt><dd>{detailsKey.last_error_status ?? 'Non disponible'}</dd><dt>Code technique</dt><dd><code>{detailsKey.last_error_code ?? 'API_KEY_TEST_FAILED'}</code></dd><dt>Message</dt><dd>{detailsKey.last_error_message ?? 'Le fournisseur n’a retourné aucun détail supplémentaire.'}</dd><dt>Date du test</dt><dd>{formatDate(detailsKey.last_error_at)}</dd></dl></div><footer><button className="account-button account-button--secondary" type="button" onClick={() => setDetailsKey(null)}>Fermer</button></footer></section></div>, document.body)}
    {confirmationDialog}
  </>
}

function Metric({ icon: Icon, value, label, tone = 'success' }: { icon: typeof KeyRound; value: string | number; label: string; tone?: 'success' | 'warning' }) { return <article className={`account-api-summary__item account-personal-api-summary__item is-${tone}`}><span className="account-api-summary__icon"><Icon size={17} aria-hidden="true" /></span><div><strong>{label}</strong><b>{tone === 'warning' ? <><TriangleAlert size={13} />{value}</> : <><Check size={13} />{value}</>}</b></div></article> }
function ApiKeyCard({ item, busy, onTest, onEdit, onDelete, onDetails }: { item: PersonalApiKey; busy: boolean; onTest: (item: PersonalApiKey) => void; onEdit: (item: PersonalApiKey) => void; onDelete: (item: PersonalApiKey) => void; onDetails: (item: PersonalApiKey) => void }) { const errored = Boolean(item.last_error_code); const brand = item.provider === 'google' ? { src: 'https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg', alt: 'Google' } : item.provider === 'stadia' ? { src: 'https://www.stadiamaps.com/favicon.ico', alt: 'Stadia Maps' } : { src: '/brands/ors-logo.jpeg', alt: 'ORS' }; const label = item.provider === 'google' ? 'Google' : item.provider === 'stadia' ? 'Stadia' : 'ORS'; return <article className={`account-api-key-card${errored ? ' is-error' : ''}`}><header><span className={`account-api-key-card__logo is-${item.provider}`}><img src={brand.src} alt={brand.alt} /></span><div><h3>{item.name}</h3><p>{label}</p></div><b className={errored ? 'is-error' : item.verified ? 'is-verified' : ''}>{errored ? 'Erreur' : item.verified ? 'Vérifiée' : 'À tester'}</b></header><div className="account-api-key-card__secret">••••••••{item.last4}</div>{errored ? <aside className="account-api-key-card__error"><TriangleAlert size={20} /><p>{item.provider === 'google' ? 'La clé Google n’autorise pas l’accès au service requis.' : item.provider === 'stadia' ? 'Clé Stadia invalide ou non reconnue.' : 'Clé ORS invalide ou non reconnue.'}<button type="button" onClick={() => onDetails(item)}>Détails</button></p></aside> : <dl><dt>Vérifiée le</dt><dd>{formatDate(item.verified_at)}</dd><dt>Dernière utilisation</dt><dd>{formatDate(item.last_used_at)}</dd></dl>}<footer><button type="button" disabled={busy} onClick={() => onTest(item)}><Play size={16} />Tester</button><div className="account-api-key-card__actions"><button type="button" aria-label={`Modifier ${item.name}`} title="Modifier" onClick={() => onEdit(item)}><Pencil size={15} /></button><button className="danger" type="button" aria-label={`Supprimer ${item.name}`} title="Supprimer" onClick={() => void onDelete(item)}><Trash2 size={15} /></button></div></footer></article> }
function formatDate(value: string | null, time = true): string { return value ? new Intl.DateTimeFormat('fr-FR', time ? { dateStyle: 'short', timeStyle: 'short' } : { dateStyle: 'short' }).format(new Date(value)) : 'Jamais' }
