// AUTO-GENERATED. DO NOT EDIT MANUALLY.
export const CATEGORY_ICON_METADATA = {
  "material-symbols:location-on-outline": ["Emplacement", "other"],
  "material-symbols:help-outline": ["Aide", "other"],
  "mdi:home-outline": ["Maison", "buildings"],
  "mdi:office-building-outline": ["Immeuble", "buildings"],
  "mdi:castle": ["Château", "buildings"],
  "mdi:bank-outline": ["Palais", "buildings"],
  "mdi:tower-fire": ["Tour de guet", "buildings"],
  "mdi:tractor": ["Ferme", "buildings"],
  "mdi:barley": ["Grange", "buildings"],
  "mdi:warehouse": ["Entrepôt", "buildings"],
  "mdi:church": ["Église", "religion"],
  "mdi:cross": ["Croix", "religion"],
  "mdi:mosque": ["Mosquée", "religion"],
  "mdi:star-david": ["Synagogue", "religion"],
  "mdi:grave-stone": ["Cimetière", "religion"],
  "mdi:temple-buddhist": ["Temple", "religion"],
  "mdi:factory": ["Usine", "industry"],
  "mdi:lightning-bolt": ["Centrale électrique", "industry"],
  "mdi:pickaxe": ["Mine", "industry"],
  "mdi:oil": ["Raffinerie", "industry"],
  "mdi:silo": ["Silo", "industry"],
  "mdi:hammer-wrench": ["Atelier", "industry"],
  "mdi:flask-outline": ["Laboratoire", "industry"],
  "mdi:wall": ["Bunker", "military"],
  "mdi:shield": ["Fort", "military"],
  "mdi:radar": ["Radar", "military"],
  "mdi:airplane": ["Aérodrome", "military"],
  "mdi:tower-beach": ["Tour de contrôle", "military"],
  "mdi:door": ["Poste frontière", "military"],
  "mdi:hospital-building": ["Hôpital", "health"],
  "mdi:medical-bag": ["Clinique", "health"],
  "mdi:pill": ["Pharmacie", "health"],
  "mdi:hot-tub": ["Thermes", "health"],
  "mdi:school-outline": ["École", "education"],
  "mdi:school": ["Université", "education"],
  "mdi:book-open-page-variant": ["Bibliothèque", "education"],
  "mdi:theater": ["Théâtre", "culture"],
  "mdi:movie-open": ["Cinéma", "culture"],
  "mdi:palette-outline": ["Musée", "culture"],
  "mdi:stadium": ["Stade", "culture"],
  "mdi:train": ["Gare", "transport"],
  "mdi:subway": ["Métro", "transport"],
  "mdi:tram": ["Tramway", "transport"],
  "mdi:bridge": ["Pont", "transport"],
  "mdi:tunnel": ["Tunnel", "transport"],
  "mdi:ferry": ["Port", "transport"],
  "mdi:road": ["Route", "transport"],
  "mdi:hotel": ["Hôtel", "tourism"],
  "mdi:silverware-fork-knife": ["Restaurant", "tourism"],
  "mdi:tent": ["Camping", "tourism"],
  "mdi:pool": ["Piscine", "tourism"],
  "mdi:water-turbine": ["Barrage", "infrastructure"],
  "mdi:water-pump": ["Château d’eau", "infrastructure"],
  "mdi:antenna": ["Antenne", "infrastructure"],
  "mdi:pipe": ["Pipeline", "infrastructure"],
  "mdi:gas-station": ["Station-service", "infrastructure"],
  "mdi:storage-tank": ["Réservoir", "infrastructure"],
  "mdi:image-filter-hdr": ["Montagne", "nature"],
  "mdi:pine-tree": ["Forêt", "nature"],
  "mdi:terrain": ["Grotte", "nature"],
  "mdi:water": ["Eau", "nature"],
  "mdi:alert": ["Danger", "access"],
  "mdi:cancel": ["Interdit", "access"],
  "mdi:lock": ["Cadenas", "access"],
  "mdi:login": ["Entrée", "access"],
  "mdi:logout": ["Sortie", "access"],
  "mdi:city": ["Ville", "buildings"],
  "mdi:garage": ["Garage", "buildings"],
  "mdi:account-tie": ["Administration", "buildings"],
  "mdi:medication-outline": ["Sanatorium", "health"],
  "mdi:book-education-outline": ["Auditorium", "culture"],
  "mdi:bus": ["Bus", "transport"],
  "mdi:airport": ["Aéroport", "transport"],
  "mdi:ferris-wheel": ["Parc d’attractions", "tourism"],
  "mdi:power-plug-outline": ["Pylône", "infrastructure"],
  "mdi:gate": ["Accès", "access"],
  "mdi:information-outline": ["Information", "other"],
  "mdi:map-marker-outline": ["Repère", "other"],
  "mdi:fire": ["Incendie", "other"],
  "mdi:shield-alert-outline": ["Sécurité", "access"],
  "mdi:barn": ["Barn", "buildings"],
  "mdi:greenhouse": ["Greenhouse", "buildings"],
  "mdi:home-city": ["Home City", "buildings"],
  "mdi:home-group": ["Home Group", "buildings"],
  "mdi:office-building-cog-outline": ["Office Building Cog", "buildings"],
  "mdi:town-hall": ["Mairie", "buildings"],
  "mdi:elevator-passenger": ["Elevator Passenger", "buildings"],
  "mdi:building": ["Building", "buildings"],
  "mdi:farm-home": ["Farm Home", "buildings"],
  "mdi:farm-home-outline": ["Farm Home", "buildings"],
  "mdi:farm-house": ["Farm House", "buildings"],
  "mdi:farm-house-outline": ["Farm House", "buildings"],
  "mdi:folder-home": ["Folder Home", "buildings"],
  "mdi:folder-home-outline": ["Folder Home", "buildings"],
  "mdi:folder-house": ["Folder House", "buildings"],
  "mdi:folder-house-outline": ["Folder House", "buildings"],
  "mdi:garage-alert": ["Garage Alert", "buildings"],
  "mdi:garage-alert-variant": ["Garage Alert", "buildings"],
  "mdi:garage-lock": ["Garage Lock", "buildings"],
  "mdi:church-outline": ["Church", "religion"],
  "mdi:candle": ["Candle", "religion"],
  "mdi:hands-pray": ["Hands Pray", "religion"],
  "mdi:book-cross": ["Book Cross", "religion"],
  "mdi:cross-celtic": ["Cross Celtic", "religion"],
  "mdi:cross-outline": ["Cross", "religion"],
  "mdi:bolnisi-cross": ["Bolnisi Cross", "religion"],
  "mdi:candle-fire": ["Candle Fire", "religion"],
  "mdi:candle-flame": ["Candle Flame", "religion"],
  "mdi:celtic-cross": ["Celtic Cross", "religion"],
  "mdi:cross-bolnisi": ["Cross Bolnisi", "religion"],
  "mdi:crossfit": ["Crossfit", "religion"],
  "mdi:crosshairs": ["Crosshairs", "religion"],
  "mdi:crosshairs-gps": ["Crosshairs Gps", "religion"],
  "mdi:crosshairs-unknown": ["Crosshairs Unknown", "religion"],
  "mdi:graveyard": ["Graveyard", "religion"],
  "mdi:human-ski-cross-country": ["Human Ski Cross Country", "religion"],
  "mdi:lacrosse": ["Lacrosse", "religion"],
  "mdi:crane": ["Crane", "industry"],
  "mdi:saw-blade": ["Saw Blade", "industry"],
  "mdi:robot-industrial": ["Robot Industrial", "industry"],
  "mdi:chemical-weapon": ["Chemical Weapon", "industry"],
  "mdi:pump": ["Pump", "industry"],
  "mdi:flask": ["Flask", "industry"],
  "mdi:boil-point": ["Boil Point", "industry"],
  "mdi:boil-point-outline": ["Boil Point", "industry"],
  "mdi:boiling-point": ["Boiling Point", "industry"],
  "mdi:circular-saw": ["Circular Saw", "industry"],
  "mdi:court-hammer": ["Court Hammer", "industry"],
  "mdi:electric-water-boiler": ["Electric Water Boiler", "industry"],
  "mdi:flask-empty": ["Flask Empty", "industry"],
  "mdi:flask-empty-minus": ["Flask Empty Minus", "industry"],
  "mdi:flask-empty-minus-outline": ["Flask Empty Minus", "industry"],
  "mdi:flask-empty-off-outline": ["Flask Empty Off", "industry"],
  "mdi:flask-empty-outline": ["Flask Empty", "industry"],
  "mdi:flask-empty-plus": ["Flask Empty Plus", "industry"],
  "mdi:tank": ["Tank", "military"],
  "mdi:gun": ["Gun", "military"],
  "mdi:target": ["Target", "military"],
  "mdi:binoculars": ["Binoculars", "military"],
  "mdi:flag": ["Flag", "military"],
  "mdi:security": ["Security", "military"],
  "mdi:airplane-alert": ["Airplane Alert", "military"],
  "mdi:airplane-car": ["Airplane Car", "military"],
  "mdi:airplane-edit": ["Airplane Edit", "military"],
  "mdi:airplane-find": ["Airplane Find", "military"],
  "mdi:airplane-gps": ["Airplane Gps", "military"],
  "mdi:airplane-landing": ["Airplane Landing", "military"],
  "mdi:airplane-marker": ["Airplane Marker", "military"],
  "mdi:airplane-minus": ["Airplane Minus", "military"],
  "mdi:ambulance": ["Ambulance", "health"],
  "mdi:stethoscope": ["Stethoscope", "health"],
  "mdi:heart-pulse": ["Heart Pulse", "health"],
  "mdi:tooth-outline": ["Tooth", "health"],
  "mdi:wheelchair-accessibility": ["Wheelchair Accessibility", "health"],
  "mdi:brain": ["Brain", "health"],
  "mdi:baby-carriage": ["Baby Carriage", "health"],
  "mdi:book-heart": ["Book Heart", "health"],
  "mdi:book-heart-outline": ["Book Heart", "health"],
  "mdi:brain-freeze": ["Brain Freeze", "health"],
  "mdi:brain-freeze-outline": ["Brain Freeze", "health"],
  "mdi:cards-heart": ["Cards Heart", "health"],
  "mdi:cards-heart-outline": ["Cards Heart", "health"],
  "mdi:library": ["Library", "education"],
  "mdi:pen": ["Pen", "education"],
  "mdi:account-school": ["Account School", "education"],
  "mdi:desk": ["Desk", "education"],
  "mdi:notebook-outline": ["Notebook", "education"],
  "mdi:calculator-variant": ["Calculator", "education"],
  "mdi:archive-lock-open": ["Archive Lock Open", "education"],
  "mdi:archive-lock-open-outline": ["Archive Lock Open", "education"],
  "mdi:audio-book": ["Audio Book", "education"],
  "mdi:audiobook": ["Audiobook", "education"],
  "mdi:bicycle-penny-farthing": ["Bicycle Penny Farthing", "education"],
  "mdi:blinds-open": ["Blinds Open", "education"],
  "mdi:book": ["Book", "education"],
  "mdi:music": ["Music", "culture"],
  "mdi:camera": ["Camera", "culture"],
  "mdi:microphone": ["Microphone", "culture"],
  "mdi:drama-masks": ["Drama Masks", "culture"],
  "mdi:guitar-electric": ["Guitar Electric", "culture"],
  "mdi:ticket-confirmation": ["Ticket Confirmation", "culture"],
  "mdi:artstation": ["Artstation", "culture"],
  "mdi:add-shopping-cart": ["Add Shopping Cart", "culture"],
  "mdi:archive-music": ["Archive Music", "culture"],
  "mdi:archive-music-outline": ["Archive Music", "culture"],
  "mdi:art": ["Art", "culture"],
  "mdi:artboard": ["Artboard", "culture"],
  "mdi:artist": ["Artist", "culture"],
  "mdi:artist-outline": ["Artist", "culture"],
  "mdi:auto-start": ["Auto Start", "culture"],
  "mdi:car": ["Car", "transport"],
  "mdi:motorcycle": ["Motorcycle", "transport"],
  "mdi:bicycle": ["Bicycle", "transport"],
  "mdi:boat": ["Boat", "transport"],
  "mdi:parking": ["Parking", "transport"],
  "mdi:traffic-light": ["Traffic Light", "transport"],
  "mdi:truck": ["Truck", "transport"],
  "mdi:taxi": ["Taxi", "transport"],
  "mdi:walk": ["Walk", "transport"],
  "mdi:train-car": ["Train Car", "transport"],
  "mdi:bus-stop": ["Bus Stop", "transport"],
  "mdi:airplane-takeoff": ["Airplane Takeoff", "transport"],
  "mdi:airplane-train": ["Airplane Train", "transport"],
  "mdi:airport-shuttle": ["Airport Shuttle", "transport"],
  "mdi:airport-taxi": ["Airport Taxi", "transport"],
  "mdi:map": ["Map", "tourism"],
  "mdi:camera-outline": ["Camera", "tourism"],
  "mdi:passport": ["Passport", "tourism"],
  "mdi:compass-outline": ["Compass", "tourism"],
  "mdi:beach": ["Beach", "tourism"],
  "mdi:luggage": ["Luggage", "tourism"],
  "mdi:food": ["Food", "tourism"],
  "mdi:coffee": ["Coffee", "tourism"],
  "mdi:hiking": ["Hiking", "tourism"],
  "mdi:ticket": ["Ticket", "tourism"],
  "mdi:bugfood": ["Bugfood", "tourism"],
  "mdi:camera-alt": ["Camera Alt", "tourism"],
  "mdi:camera-burst": ["Camera Burst", "tourism"],
  "mdi:camera-control": ["Camera Control", "tourism"],
  "mdi:camera-document": ["Camera Document", "tourism"],
  "mdi:transmission-tower": ["Transmission Tower", "infrastructure"],
  "mdi:solar-power": ["Solar Power", "infrastructure"],
  "mdi:wind-turbine": ["Wind Turbine", "infrastructure"],
  "mdi:electric-switch": ["Electric Switch", "infrastructure"],
  "mdi:fire-hydrant": ["Fire Hydrant", "infrastructure"],
  "mdi:meter-electric": ["Meter Electric", "infrastructure"],
  "mdi:accelerometer": ["Accelerometer", "infrastructure"],
  "mdi:altimeter": ["Altimeter", "infrastructure"],
  "mdi:barometer": ["Barometer", "infrastructure"],
  "mdi:bicycle-electric": ["Bicycle Electric", "infrastructure"],
  "mdi:bike-electric": ["Bike Electric", "infrastructure"],
  "mdi:branding-watermark": ["Branding Watermark", "infrastructure"],
  "mdi:bus-electric": ["Bus Electric", "infrastructure"],
  "mdi:tree": ["Tree", "nature"],
  "mdi:flower": ["Flower", "nature"],
  "mdi:leaf": ["Leaf", "nature"],
  "mdi:weather-sunny": ["Weather Sunny", "nature"],
  "mdi:weather-rainy": ["Weather Rainy", "nature"],
  "mdi:weather-lightning": ["Weather Lightning", "nature"],
  "mdi:island": ["Island", "nature"],
  "mdi:waves": ["Waves", "nature"],
  "mdi:fish": ["Fish", "nature"],
  "mdi:paw": ["Paw", "nature"],
  "mdi:sprout": ["Sprout", "nature"],
  "mdi:bee": ["Bee", "nature"],
  "mdi:all-terrain-vehicle": ["All Terrain Vehicle", "nature"],
  "mdi:bee-flower": ["Bee Flower", "nature"],
  "mdi:key": ["Key", "access"],
  "mdi:door-open": ["Door Open", "access"],
  "mdi:elevator": ["Elevator", "access"],
  "mdi:stairs": ["Stairs", "access"],
  "mdi:exit-run": ["Exit Run", "access"],
  "mdi:barrier": ["Barrier", "access"],
  "mdi:lock-alert": ["Lock Alert", "access"],
  "mdi:access-point": ["Access Point", "access"],
  "mdi:access-point-minus": ["Access Point Minus", "access"],
  "mdi:help-circle-outline": ["Help Circle", "other"],
  "mdi:map-search-outline": ["Map Search", "other"],
  "mdi:shape-outline": ["Shape", "other"],
  "mdi:tools": ["Tools", "other"],
  "mdi:post": ["Post", "urban"],
  "mdi:mailbox": ["Mailbox", "urban"],
  "mdi:bench": ["Bench", "urban"],
  "mdi:fountain": ["Fountain", "urban"],
  "mdi:recycle": ["Recycle", "urban"],
  "mdi:sign-direction": ["Sign Direction", "urban"],
  "mdi:bench-back": ["Bench Back", "urban"],
  "mdi:broadcast": ["Broadcast", "urban"],
  "mdi:store": ["Store", "commerce"],
  "mdi:storefront": ["Storefront", "commerce"],
  "mdi:cart": ["Cart", "commerce"],
  "mdi:basket": ["Basket", "commerce"],
  "mdi:cash-register": ["Cash Register", "commerce"],
  "mdi:credit-card": ["Credit Card", "commerce"],
  "mdi:bank": ["Bank", "commerce"],
  "mdi:tag": ["Tag", "commerce"],
  "mdi:bed": ["Bed", "accommodation"],
  "mdi:bed-outline": ["Bed", "accommodation"],
  "mdi:home-heart": ["Home Heart", "accommodation"],
  "mdi:room-service-outline": ["Room Service", "accommodation"],
  "mdi:shower": ["Shower", "accommodation"],
  "mdi:bathtub-outline": ["Bathtub", "accommodation"],
  "mdi:sofa-outline": ["Sofa", "accommodation"],
  "mdi:fireplace": ["Fireplace", "accommodation"],
  "mdi:scale-balance": ["Tribunal", "administration"],
  "mdi:gavel": ["Gavel", "administration"],
  "mdi:file-document-outline": ["File Document", "administration"],
  "mdi:briefcase-outline": ["Briefcase", "administration"],
  "mdi:shield-account": ["Shield Account", "administration"],
  "mdi:office-building": ["Office Building", "administration"],
  "mdi:police-station": ["Prison", "administration"],
  "mdi:clipboard-text-outline": ["Clipboard Text", "administration"],
  "mdi:pillar": ["Pillar", "heritage"],
  "mdi:arch": ["Arch", "heritage"],
  "mdi:map-marker-star": ["Map Marker Star", "heritage"],
  "mdi:trophy-outline": ["Trophy", "heritage"],
  "mdi:medal-outline": ["Medal", "heritage"],
  "mdi:history": ["History", "heritage"],
  "mdi:clock-outline": ["Clock", "heritage"],
  "mdi:airplane-search": ["Airplane Search", "heritage"],
} as const satisfies Readonly<Record<string, readonly [label: string, group: string]>>

export const CATEGORY_ICON_COUNT = 1500
