// AUTO-GENERATED. DO NOT EDIT MANUALLY.
export const CATEGORY_ICON_LAZY_METADATA = {
  "mdi:apple": ["Pomme", "gastronomy"],
  "mdi:baguette": ["Baguette", "gastronomy"],
  "mdi:beer": ["Bière", "gastronomy"],
  "mdi:blender": ["Mixeur", "gastronomy"],
  "mdi:bread": ["Pain", "gastronomy"],
  "mdi:cake": ["Cake", "gastronomy"],
  "mdi:candycane": ["Sucrerie", "gastronomy"],
  "mdi:carrot": ["Carotte", "gastronomy"],
  "mdi:cheese": ["Fromage", "gastronomy"],
  "mdi:cookie": ["Biscuit", "gastronomy"],
  "mdi:corn": ["Maïs", "gastronomy"],
  "mdi:cupcake": ["Pâtisserie", "gastronomy"],
  "mdi:egg": ["Œuf", "gastronomy"],
  "mdi:glass": ["Verre", "gastronomy"],
  "mdi:grill": ["Grill", "gastronomy"],
  "mdi:hamburger": ["Hamburger", "gastronomy"],
  "mdi:kettle": ["Bouilloire", "gastronomy"],
  "mdi:muffin": ["Muffin", "gastronomy"],
  "mdi:noodles": ["Nouilles", "gastronomy"],
  "mdi:pasta": ["Pâtes", "gastronomy"],
  "mdi:peanut": ["Cacahuète", "gastronomy"],
  "mdi:pizza": ["Pizza", "gastronomy"],
  "mdi:popcorn": ["Pop-corn", "gastronomy"],
  "mdi:pot": ["Marmite", "gastronomy"],
  "mdi:pretzel": ["Bretzel", "gastronomy"],
  "mdi:restaurant": ["Restaurant", "gastronomy"],
  "mdi:rice": ["Riz", "gastronomy"],
  "mdi:sausage": ["Sausage", "gastronomy"],
  "mdi:silverware": ["Couverts", "gastronomy"],
  "mdi:taco": ["Taco", "gastronomy"],
  "mdi:tea": ["Thé", "gastronomy"],
  "mdi:wine": ["Vin", "gastronomy"],
  "mdi:apple-airplay": ["Pomme airplay", "gastronomy"],
  "mdi:apple-finder": ["Pomme finder", "gastronomy"],
  "mdi:apple-icloud": ["Pomme icloud", "gastronomy"],
  "mdi:apple-ios": ["Pomme ios", "gastronomy"],
  "mdi:apple-ipod": ["Pomme ipod", "gastronomy"],
  "mdi:apple-mobileme": ["Pomme mobileme", "gastronomy"],
  "mdi:apple-safari": ["Pomme safari", "gastronomy"],
  "mdi:asian-noodles": ["Asian nouilles", "gastronomy"],
  "mdi:basket-fill": ["Basket fill", "gastronomy"],
  "mdi:basket-unfill": ["Basket unfill", "gastronomy"],
  "mdi:bicycle-basket": ["Vélo basket", "gastronomy"],
  "mdi:bike-basket": ["Bike basket", "gastronomy"],
  "mdi:birthday-cake": ["Birthday cake", "gastronomy"],
  "mdi:blender-software": ["Mixeur software", "gastronomy"],
  "mdi:bottle-soda": ["Bouteille soda", "gastronomy"],
  "mdi:bottle-wine": ["Bouteille vin", "gastronomy"],
  "mdi:bread-slice": ["Boulangerie", "gastronomy"],
  "mdi:cake-layered": ["Cake layered", "gastronomy"],
  "mdi:cake-variant": ["Cake variante", "gastronomy"],
  "mdi:chef-hat": ["Chef hat", "gastronomy"],
  "mdi:chili-hot": ["Piment hot", "gastronomy"],
  "mdi:chili-medium": ["Piment medium", "gastronomy"],
  "mdi:chili-mild": ["Piment mild", "gastronomy"],
  "mdi:coffee-machine": ["Café machine", "gastronomy"],
  "mdi:coffee-maker": ["Café maker", "gastronomy"],
  "mdi:cookie-clock": ["Biscuit clock", "gastronomy"],
  "mdi:cookie-cog": ["Biscuit cog", "gastronomy"],
  "mdi:cookie-crumbs": ["Biscuit crumbs", "gastronomy"],
  "mdi:cookie-lock": ["Biscuit verrou", "gastronomy"],
  "mdi:egg-easter": ["Œuf easter", "gastronomy"],
  "mdi:egg-fried": ["Œuf fried", "gastronomy"],
  "mdi:fast-food": ["Fast restauration", "gastronomy"],
  "mdi:fish-food": ["Fish restauration", "gastronomy"],
  "mdi:food-allergy": ["Restauration allergy", "gastronomy"],
  "mdi:food-apple": ["Restauration pomme", "gastronomy"],
  "mdi:food-croissant": ["Restauration croissant", "gastronomy"],
  "mdi:food-drumstick": ["Restauration drumstick", "gastronomy"],
  "mdi:food-frankfurter": ["Restauration frankfurter", "gastronomy"],
  "mdi:food-halal": ["Restauration halal", "gastronomy"],
  "mdi:food-italian": ["Restauration italian", "gastronomy"],
  "mdi:food-jewish": ["Restauration jewish", "gastronomy"],
  "mdi:food-kosher": ["Restauration kosher", "gastronomy"],
  "mdi:food-muslim": ["Restauration muslim", "gastronomy"],
  "mdi:food-processor": ["Restauration processor", "gastronomy"],
  "mdi:food-ramen": ["Restauration ramen", "gastronomy"],
  "mdi:food-steak": ["Restauration steak", "gastronomy"],
  "mdi:food-turkey": ["Restauration turkey", "gastronomy"],
  "mdi:food-variant": ["Restauration variante", "gastronomy"],
  "mdi:food-weiner": ["Restauration weiner", "gastronomy"],
  "mdi:french-baguette": ["French baguette", "gastronomy"],
  "mdi:fruit-ananas": ["Fruit ananas", "gastronomy"],
  "mdi:fruit-cherries": ["Fruit cherries", "gastronomy"],
  "mdi:fruit-citrus": ["Fruit citrus", "gastronomy"],
  "mdi:fruit-grapes": ["Fruit grapes", "gastronomy"],
  "mdi:fruit-lemon": ["Fruit lemon", "gastronomy"],
  "mdi:fruit-lime": ["Fruit lime", "gastronomy"],
  "mdi:fruit-pear": ["Fruit pear", "gastronomy"],
  "mdi:fruit-pineapple": ["Fruit pineapple", "gastronomy"],
  "mdi:fruit-watermelon": ["Fruit watermelon", "gastronomy"],
  "mdi:glass-cocktail": ["Verre cocktail", "gastronomy"],
  "mdi:glass-flute": ["Verre flute", "gastronomy"],
  "mdi:glass-liquid": ["Verre liquid", "gastronomy"],
  "mdi:glass-mug": ["Verre mug", "gastronomy"],
  "mdi:glass-stange": ["Verre stange", "gastronomy"],
  "mdi:glass-tulip": ["Verre tulipe", "gastronomy"],
  "mdi:glass-water": ["Verre eau", "gastronomy"],
  "mdi:glass-wine": ["Verre vin", "gastronomy"],
  "mdi:ice-cream": ["Glace cream", "gastronomy"],
  "mdi:kettle-steam": ["Bouilloire vapeur", "gastronomy"],
  "mdi:local-pizza": ["Local pizza", "gastronomy"],
  "mdi:local-restaurant": ["Local restaurant", "gastronomy"],
  "mdi:pot-steam": ["Marmite vapeur", "gastronomy"],
  "mdi:shopping-basket": ["Courses basket", "gastronomy"],
  "mdi:silverware-clean": ["Couverts clean", "gastronomy"],
  "mdi:silverware-fork": ["Couverts fork", "gastronomy"],
  "mdi:silverware-knife": ["Couverts knife", "gastronomy"],
  "mdi:silverware-shimmer": ["Couverts brillant", "gastronomy"],
  "mdi:silverware-spoon": ["Couverts cuillère", "gastronomy"],
  "mdi:silverware-variant": ["Couverts variante", "gastronomy"],
  "mdi:swiss-cheese": ["Swiss fromage", "gastronomy"],
  "mdi:tea-kettle": ["Thé bouilloire", "gastronomy"],
  "mdi:basket-outline": ["Basket contour", "gastronomy"],
  "mdi:beer-outline": ["Bière contour", "gastronomy"],
  "mdi:blender-outline": ["Mixeur contour", "gastronomy"],
  "mdi:bottle-soda-classic": ["Bouteille soda classic", "gastronomy"],
  "mdi:coffee-outline": ["Café contour", "gastronomy"],
  "mdi:coffee-to-go": ["Café to go", "gastronomy"],
  "mdi:cookie-outline": ["Biscuit contour", "gastronomy"],
  "mdi:drone": ["Drone", "photography"],
  "mdi:film": ["Film", "photography"],
  "mdi:image": ["Image", "photography"],
  "mdi:panorama": ["Panorama", "photography"],
  "mdi:telescope": ["Astronomie", "photography"],
  "mdi:video": ["Vidéo", "photography"],
  "mdi:audio-video": ["Audio vidéo", "photography"],
  "mdi:book-image": ["Livre image", "photography"],
  "mdi:camera-account": ["Appareil photo personne", "photography"],
  "mdi:camera-enhance": ["Appareil photo enhance", "photography"],
  "mdi:camera-flip": ["Appareil photo flip", "photography"],
  "mdi:camera-focus": ["Appareil photo focus", "photography"],
  "mdi:camera-front": ["Appareil photo front", "photography"],
  "mdi:camera-gopro": ["Appareil photo gopro", "photography"],
  "mdi:camera-image": ["Appareil photo image", "photography"],
  "mdi:camera-iris": ["Appareil photo iris", "photography"],
  "mdi:camera-location": ["Appareil photo emplacement", "photography"],
  "mdi:camera-marker": ["Appareil photo repère", "photography"],
  "mdi:camera-rear": ["Appareil photo arrière", "photography"],
  "mdi:camera-roll": ["Appareil photo pellicule", "photography"],
  "mdi:film-open": ["Film ouvert", "photography"],
  "mdi:film-reel": ["Film bobine", "photography"],
  "mdi:film-star": ["Film étoile", "photography"],
  "mdi:focus-auto": ["Focus automatique", "photography"],
  "mdi:focus-field": ["Focus champ", "photography"],
  "mdi:image-360": ["Image 360", "photography"],
  "mdi:image-album": ["Image album", "photography"],
  "mdi:image-area": ["Image zone", "photography"],
  "mdi:image-description": ["Image description", "photography"],
  "mdi:image-filter": ["Image filtre", "photography"],
  "mdi:image-frame": ["Image cadre", "photography"],
  "mdi:image-location": ["Image emplacement", "photography"],
  "mdi:image-marker": ["Image repère", "photography"],
  "mdi:image-multiple": ["Image multiple", "photography"],
  "mdi:image-search": ["Image recherche", "photography"],
  "mdi:image-text": ["Image text", "photography"],
  "mdi:image-vr": ["Image vr", "photography"],
  "mdi:moon-full": ["Lune full", "photography"],
  "mdi:moon-new": ["Lune new", "photography"],
  "mdi:panorama-360": ["Panorama 360", "photography"],
  "mdi:panorama-fisheye": ["Panorama fisheye", "photography"],
  "mdi:panorama-horizontal": ["Panorama horizontal", "photography"],
  "mdi:panorama-sphere": ["Panorama sphere", "photography"],
  "mdi:panorama-variant": ["Panorama variante", "photography"],
  "mdi:panorama-vertical": ["Panorama vertical", "photography"],
  "mdi:backpack": ["Sac à dos", "hiking"],
  "mdi:campfire": ["Feu de camp", "hiking"],
  "mdi:compass": ["Boussole", "hiking"],
  "mdi:compass-rose": ["Boussole rose", "hiking"],
  "mdi:directions-walk": ["Itinéraire marche", "hiking"],
  "mdi:human-hiking": ["Personne randonnée", "hiking"],
  "mdi:human-walk": ["Personne marche", "hiking"],
  "mdi:shoe-print": ["Chaussure empreinte", "hiking"],
  "mdi:shoe-running": ["Chaussure running", "hiking"],
  "mdi:shoe-sneaker": ["Chaussure basket", "hiking"],
  "mdi:sign-pole": ["Sign poteau", "hiking"],
  "mdi:backpack-outline": ["Sac à dos contour", "hiking"],
  "mdi:map-marker-distance": ["Carte repère distance", "hiking"],
  "mdi:map-marker-path": ["Carte repère sentier", "hiking"],
  "mdi:diving": ["Plongée", "water"],
  "mdi:lake": ["Lac", "water"],
  "mdi:sprinkler": ["Sprinkler", "water"],
  "mdi:swim": ["Nage", "water"],
  "mdi:waterfall": ["Cascade", "water"],
  "mdi:wave": ["Vague", "water"],
  "mdi:chart-waterfall": ["Chart cascade", "water"],
  "mdi:cup-water": ["Cup eau", "water"],
  "mdi:diving-flippers": ["Plongée flippers", "water"],
  "mdi:diving-helmet": ["Plongée helmet", "water"],
  "mdi:diving-scuba": ["Plongée plongée", "water"],
  "mdi:diving-snorkel": ["Plongée snorkel", "water"],
  "mdi:drink-water": ["Drink eau", "water"],
  "mdi:hand-water": ["Hand eau", "water"],
  "mdi:heat-wave": ["Heat vague", "water"],
  "mdi:human-diving": ["Personne plongée", "water"],
  "mdi:hydro-power": ["Hydro énergie", "water"],
  "mdi:pool-rack": ["Piscine rack", "water"],
  "mdi:pool-temperature": ["Piscine température", "water"],
  "mdi:ski-water": ["Ski eau", "water"],
  "mdi:sprinkler-head": ["Sprinkler head", "water"],
  "mdi:sprinkler-mist": ["Sprinkler brume", "water"],
  "mdi:sprinkler-variant": ["Sprinkler variante", "water"],
  "mdi:swim-dive": ["Nage plongée", "water"],
  "mdi:swimming-pool": ["Natation piscine", "water"],
  "mdi:water-alert": ["Eau alerte", "water"],
  "mdi:water-circle": ["Eau cercle", "water"],
  "mdi:water-drop": ["Eau goutte", "water"],
  "mdi:water-evaporation": ["Eau évaporation", "water"],
  "mdi:water-flow": ["Eau écoulement", "water"],
  "mdi:water-saver": ["Eau économie", "water"],
  "mdi:water-temperature": ["Eau température", "water"],
  "mdi:water-transparent": ["Eau transparent", "water"],
  "mdi:water-truck": ["Eau camion", "water"],
  "mdi:water-well": ["Eau well", "water"],
  "mdi:wave-undercurrent": ["Vague courant", "water"],
  "mdi:diving-scuba-flag": ["Plongée plongée flag", "water"],
  "mdi:diving-scuba-mask": ["Plongée plongée mask", "water"],
  "mdi:diving-scuba-tank": ["Plongée plongée tank", "water"],
  "mdi:human-ski-water": ["Personne ski eau", "water"],
  "mdi:water-outline": ["Eau contour", "water"],
  "mdi:diving-scuba-tank-multiple": ["Plongée plongée tank multiple", "water"],
  "mdi:water-alert-outline": ["Eau alerte contour", "water"],
  "mdi:water-drop-outline": ["Eau goutte contour", "water"],
  "mdi:water-temperature-outline": ["Eau température contour", "water"],
  "mdi:water-well-outline": ["Eau well contour", "water"],
  "mdi:landslide": ["Glissement de terrain", "mountain"],
  "mdi:mountain": ["Montagne", "mountain"],
  "mdi:ski": ["Ski", "mountain"],
  "mdi:snowflake": ["Neige", "mountain"],
  "mdi:summit": ["Sommet", "mountain"],
  "mdi:volcano": ["Volcan", "mountain"],
  "mdi:human-ski": ["Personne ski", "mountain"],
  "mdi:rock-climbing": ["Rocher escalade", "mountain"],
  "mdi:snowflake-alert": ["Neige alerte", "mountain"],
  "mdi:snowflake-melt": ["Neige melt", "mountain"],
  "mdi:snowflake-temperature": ["Neige température", "mountain"],
  "mdi:snowflake-variant": ["Neige variante", "mountain"],
  "mdi:bike-pedal-mountain": ["Bike pedal montagne", "mountain"],
  "mdi:landslide-outline": ["Glissement de terrain contour", "mountain"],
  "mdi:mountain-outline": ["Montagne contour", "mountain"],
  "mdi:ski-cross-country": ["Ski croix pays", "mountain"],
  "mdi:volcano-outline": ["Volcan contour", "mountain"],
  "mdi:image-filter-hdr-outline": ["Image filtre hdr contour", "mountain"],
  "mdi:cow": ["Cow", "agriculture"],
  "mdi:farm": ["Ferme", "agriculture"],
  "mdi:horse": ["Horse", "agriculture"],
  "mdi:pig": ["Pig", "agriculture"],
  "mdi:pitchfork": ["Pitchfork", "agriculture"],
  "mdi:seed": ["Seed", "agriculture"],
  "mdi:sheep": ["Sheep", "agriculture"],
  "mdi:shovel": ["Shovel", "agriculture"],
  "mdi:wheat": ["Wheat", "agriculture"],
  "mdi:chart-tree": ["Chart arbre", "agriculture"],
  "mdi:chess-horse": ["Chess horse", "agriculture"],
  "mdi:emoji-cow": ["Emoji cow", "agriculture"],
  "mdi:emoji-pig": ["Emoji pig", "agriculture"],
  "mdi:emoji-sheep": ["Emoji sheep", "agriculture"],
  "mdi:emoticon-cow": ["Emoticon cow", "agriculture"],
  "mdi:emoticon-pig": ["Emoticon pig", "agriculture"],
  "mdi:emoticon-sheep": ["Emoticon sheep", "agriculture"],
  "mdi:family-tree": ["Family arbre", "agriculture"],
  "mdi:horse-human": ["Horse personne", "agriculture"],
  "mdi:horse-riding": ["Horse riding", "agriculture"],
  "mdi:horse-variant": ["Horse variante", "agriculture"],
  "mdi:palm-tree": ["Palm arbre", "agriculture"],
  "mdi:pig-variant": ["Pig variante", "agriculture"],
  "mdi:report-tree": ["Report arbre", "agriculture"],
  "mdi:seed-add": ["Seed ajout", "agriculture"],
  "mdi:tractor-variant": ["Tractor variante", "agriculture"],
  "mdi:watering-can": ["Watering can", "agriculture"],
  "mdi:watering-pot": ["Watering marmite", "agriculture"],
  "mdi:widget-tree": ["Widget arbre", "agriculture"],
  "mdi:farm-outline": ["Ferme contour", "agriculture"],
  "mdi:horse-variant-fast": ["Horse variante fast", "agriculture"],
  "mdi:pine-tree-box": ["Pin arbre box", "agriculture"],
  "mdi:pine-tree-fire": ["Pin arbre incendie", "agriculture"],
  "mdi:pine-tree-multiple": ["Pin arbre multiple", "agriculture"],
  "mdi:pine-tree-variant": ["Pin arbre variante", "agriculture"],
  "mdi:seed-outline": ["Seed contour", "agriculture"],
  "mdi:sprout-outline": ["Sprout contour", "agriculture"],
  "mdi:tree-outline": ["Arbre contour", "agriculture"],
  "mdi:fruit-grapes-outline": ["Fruit grapes contour", "agriculture"],
  "mdi:pig-variant-outline": ["Pig variante contour", "agriculture"],
  "mdi:battery": ["Battery", "energy"],
  "mdi:electricity": ["Electricity", "energy"],
  "mdi:fuel": ["Carburant", "energy"],
  "mdi:power": ["Énergie", "energy"],
  "mdi:battery-0": ["Battery 0", "energy"],
  "mdi:battery-10": ["Battery 10", "energy"],
  "mdi:battery-100": ["Battery 100", "energy"],
  "mdi:battery-20": ["Battery 20", "energy"],
  "mdi:battery-30": ["Battery 30", "energy"],
  "mdi:battery-40": ["Battery 40", "energy"],
  "mdi:battery-50": ["Battery 50", "energy"],
  "mdi:battery-60": ["Battery 60", "energy"],
  "mdi:battery-70": ["Battery 70", "energy"],
  "mdi:battery-80": ["Battery 80", "energy"],
  "mdi:battery-90": ["Battery 90", "energy"],
  "mdi:battery-add": ["Battery ajout", "energy"],
  "mdi:battery-alert": ["Battery alerte", "energy"],
  "mdi:battery-backup": ["Battery backup", "energy"],
  "mdi:battery-bluetooth": ["Battery bluetooth", "energy"],
  "mdi:battery-charging": ["Battery charging", "energy"],
  "mdi:battery-clock": ["Battery clock", "energy"],
  "mdi:battery-eco": ["Battery eco", "energy"],
  "mdi:battery-empty": ["Battery empty", "energy"],
  "mdi:battery-full": ["Battery full", "energy"],
  "mdi:battery-heart": ["Battery heart", "energy"],
  "mdi:battery-high": ["Battery high", "energy"],
  "mdi:battery-lock": ["Battery verrou", "energy"],
  "mdi:battery-low": ["Battery low", "energy"],
  "mdi:battery-medium": ["Battery medium", "energy"],
  "mdi:battery-negative": ["Battery negative", "energy"],
  "mdi:battery-positive": ["Battery positive", "energy"],
  "mdi:battery-recycle": ["Battery recycle", "energy"],
  "mdi:battery-saver": ["Battery économie", "energy"],
  "mdi:battery-standard": ["Battery standard", "energy"],
  "mdi:battery-std": ["Battery std", "energy"],
  "mdi:battery-unknown": ["Battery unknown", "energy"],
  "mdi:battery-warning": ["Battery warning", "energy"],
  "mdi:car-battery": ["Voiture battery", "energy"],
  "mdi:car-electric": ["Voiture electric", "energy"],
  "mdi:car-transmission": ["Voiture transmission", "energy"],
  "mdi:electric-charger": ["Electric charger", "energy"],
  "mdi:electricity-circle": ["Electricity cercle", "energy"],
  "mdi:electricity-generator": ["Electricity generator", "energy"],
  "mdi:fence-electric": ["Fence electric", "energy"],
  "mdi:fossil-fuel": ["Fossil carburant", "energy"],
  "mdi:anchor": ["Ancre", "maritime"],
  "mdi:lighthouse": ["Phare", "maritime"],
  "mdi:pier": ["Jetée", "maritime"],
  "mdi:rowing": ["Rowing", "maritime"],
  "mdi:ship": ["Ship", "maritime"],
  "mdi:submarine": ["Submarine", "maritime"],
  "mdi:cargo-ship": ["Cargo ship", "maritime"],
  "mdi:directions-boat": ["Itinéraire bateau", "maritime"],
  "mdi:directions-ferry": ["Itinéraire ferry", "maritime"],
  "mdi:human-rowing": ["Personne rowing", "maritime"],
  "mdi:lighthouse-on": ["Phare on", "maritime"],
  "mdi:pier-crane": ["Jetée crane", "maritime"],
  "mdi:sail-boat": ["Sail bateau", "maritime"],
  "mdi:ship-wheel": ["Ship wheel", "maritime"],
  "mdi:panorama-fish-eye": ["Panorama fish eye", "maritime"],
  "mdi:sail-boat-crash": ["Sail bateau crash", "maritime"],
  "mdi:sail-boat-sink": ["Sail bateau sink", "maritime"],
  "mdi:sail-boat-wreck": ["Sail bateau wreck", "maritime"],
  "mdi:fish-food-outline": ["Fish restauration contour", "maritime"],
  "mdi:badminton": ["Badminton", "sport"],
  "mdi:baseball": ["Baseball", "sport"],
  "mdi:basketball": ["Basketball", "sport"],
  "mdi:bike": ["Bike", "sport"],
  "mdi:dumbbell": ["Dumbbell", "sport"],
  "mdi:football": ["Football", "sport"],
  "mdi:golf": ["Golf", "sport"],
  "mdi:karate": ["Karate", "sport"],
  "mdi:medal": ["Medal", "sport"],
  "mdi:rugby": ["Rugby", "sport"],
  "mdi:run": ["Run", "sport"],
  "mdi:snowboard": ["Snowboard", "sport"],
  "mdi:soccer": ["Soccer", "sport"],
  "mdi:tennis": ["Tennis", "sport"],
  "mdi:trophy": ["Trophy", "sport"],
  "mdi:volleyball": ["Volleyball", "sport"],
  "mdi:weight": ["Weight", "sport"],
  "mdi:baseball-bat": ["Baseball bat", "sport"],
  "mdi:baseball-diamond": ["Baseball diamond", "sport"],
  "mdi:basketball-hoop": ["Basketball hoop", "sport"],
  "mdi:bicycle-antique": ["Vélo antique", "sport"],
  "mdi:bicycle-cargo": ["Vélo cargo", "sport"],
  "mdi:bike-cargo": ["Bike cargo", "sport"],
  "mdi:bike-fast": ["Bike fast", "sport"],
  "mdi:bike-pedal": ["Bike pedal", "sport"],
  "mdi:boxing-glove": ["Boxing glove", "sport"],
  "mdi:boxing-gloves": ["Boxing gloves", "sport"],
  "mdi:directions-bike": ["Itinéraire bike", "sport"],
  "mdi:directions-run": ["Itinéraire run", "sport"],
  "mdi:football-american": ["Football american", "sport"],
  "mdi:football-australian": ["Football australian", "sport"],
  "mdi:football-helmet": ["Football helmet", "sport"],
  "mdi:football-pitch": ["Football pitch", "sport"],
  "mdi:football-play": ["Football play", "sport"],
  "mdi:golf-cart": ["Golf cart", "sport"],
  "mdi:golf-course": ["Golf course", "sport"],
  "mdi:golf-tee": ["Golf tee", "sport"],
  "mdi:hand-bike": ["Hand bike", "sport"],
  "mdi:hockey-puck": ["Hockey puck", "sport"],
  "mdi:hockey-sticks": ["Hockey sticks", "sport"],
  "mdi:human-karate": ["Personne karate", "sport"],
  "mdi:human-run": ["Personne run", "sport"],
  "mdi:human-snowboard": ["Personne snowboard", "sport"],
  "mdi:rugby-ball": ["Rugby ball", "sport"],
  "mdi:run-fast": ["Run fast", "sport"],
  "mdi:soccer-field": ["Soccer champ", "sport"],
  "mdi:stadium-variant": ["Stadium variante", "sport"],
  "mdi:table-tennis": ["Table tennis", "sport"],
  "mdi:tennis-ball": ["Tennis ball", "sport"],
  "mdi:tennis-racket": ["Tennis racket", "sport"],
  "mdi:tennis-racquet": ["Tennis racquet", "sport"],
  "mdi:trophy-award": ["Trophy award", "sport"],
  "mdi:trophy-broken": ["Trophy broken", "sport"],
  "mdi:trophy-variant": ["Trophy variante", "sport"],
  "mdi:weight-gram": ["Weight gram", "sport"],
  "mdi:weight-kg": ["Weight kg", "sport"],
  "mdi:weight-kilogram": ["Weight kilogram", "sport"],
  "mdi:weight-lb": ["Weight lb", "sport"],
  "mdi:weight-lifter": ["Weight lifter", "sport"],
  "mdi:weight-pound": ["Weight pound", "sport"],
  "mdi:baseball-outline": ["Baseball contour", "sport"],
  "mdi:bicycle-high-wheel": ["Vélo high wheel", "sport"],
  "mdi:bike-pedal-clipless": ["Bike pedal clipless", "sport"],
  "mdi:bike-pedal-flat": ["Bike pedal flat", "sport"],
  "mdi:human-run-fast": ["Personne run fast", "sport"],
  "mdi:stadium-outline": ["Stadium contour", "sport"],
  "mdi:baseball-diamond-outline": ["Baseball diamond contour", "sport"],
  "mdi:bone": ["Os", "archaeology"],
  "mdi:excavator": ["Excavatrice", "archaeology"],
  "mdi:skull": ["Crâne", "archaeology"],
  "mdi:change-history": ["Change histoire", "archaeology"],
  "mdi:skull-crossbones": ["Crâne croisés", "archaeology"],
  "mdi:skull-scan": ["Crâne scan", "archaeology"],
  "mdi:treasure-chest": ["Trésor chest", "archaeology"],
  "mdi:pot-outline": ["Marmite contour", "archaeology"],
  "mdi:skull-outline": ["Crâne contour", "archaeology"],
  "mdi:skull-crossbones-outline": ["Crâne croisés contour", "archaeology"],
  "mdi:skull-scan-outline": ["Crâne scan contour", "archaeology"],
  "mdi:treasure-chest-outline": ["Trésor chest contour", "archaeology"],
  "mdi:cemetery": ["Cimetière (cemetery)", "religion"],
  "mdi:coffin": ["Coffin", "religion"],
  "mdi:islam": ["Islam", "religion"],
  "mdi:khanda": ["Khanda", "religion"],
  "mdi:meditation": ["Meditation", "religion"],
  "mdi:menorah": ["Menorah", "religion"],
  "mdi:om": ["Om", "religion"],
  "mdi:synagogue": ["Synagogue (synagogue)", "religion"],
  "mdi:temple": ["Temple (temple)", "religion"],
  "mdi:human-meditation": ["Personne meditation", "religion"],
  "mdi:menorah-fire": ["Menorah incendie", "religion"],
  "mdi:menorah-flame": ["Menorah flame", "religion"],
  "mdi:shield-cross": ["Protection croix", "religion"],
  "mdi:swiss-cross": ["Swiss croix", "religion"],
  "mdi:sword-cross": ["Sword croix", "religion"],
  "mdi:temple-hindu": ["Temple hindu", "religion"],
  "mdi:mosque-outline": ["Mosquée contour", "religion"],
  "mdi:swiss-cross-box": ["Swiss croix box", "religion"],
  "mdi:synagogue-outline": ["Synagogue contour", "religion"],
  "mdi:temple-outline": ["Temple contour", "religion"],
  "mdi:shield-cross-outline": ["Protection croix contour", "religion"],
  "mdi:temple-buddhist-outline": ["Temple buddhist contour", "religion"],
  "mdi:temple-hindu-outline": ["Temple hindu contour", "religion"],
  "mdi:swiss-cross-box-outline": ["Swiss croix box contour", "religion"],
  "mdi:ammunition": ["Ammunition", "military"],
  "mdi:bomb": ["Bomb", "military"],
  "mdi:parachute": ["Parachute", "military"],
  "mdi:pistol": ["Pistol", "military"],
  "mdi:sword": ["Sword", "military"],
  "mdi:account-security": ["Personne sécurité", "military"],
  "mdi:airplane-clock": ["Avion clock", "military"],
  "mdi:airplane-cog": ["Avion cog", "military"],
  "mdi:airplane-date": ["Avion date", "military"],
  "mdi:airplane-location": ["Avion emplacement", "military"],
  "mdi:airplane-schedule": ["Avion schedule", "military"],
  "mdi:airplane-tick": ["Avion tick", "military"],
  "mdi:airplane-time": ["Avion time", "military"],
  "mdi:ammunition-pistol": ["Ammunition pistol", "military"],
  "mdi:ammunition-rifle": ["Ammunition rifle", "military"],
  "mdi:atomic-bomb": ["Atomic bomb", "military"],
  "mdi:car-security": ["Voiture sécurité", "military"],
  "mdi:cloud-security": ["Cloud sécurité", "military"],
  "mdi:flag-add": ["Flag ajout", "military"],
  "mdi:flag-checkered": ["Flag checkered", "military"],
  "mdi:flag-triangle": ["Flag triangle", "military"],
  "mdi:flag-variant": ["Flag variante", "military"],
  "mdi:gas-tank": ["Gaz tank", "military"],
  "mdi:magazine-pistol": ["Magazine pistol", "military"],
  "mdi:oxygen-tank": ["Oxygen tank", "military"],
  "mdi:bandage": ["Bandage", "health"],
  "mdi:doctor": ["Doctor", "health"],
  "mdi:hospital": ["Hôpital (hospital)", "health"],
  "mdi:medication": ["Medication", "health"],
  "mdi:medicine": ["Medicine", "health"],
  "mdi:needle": ["Needle", "health"],
  "mdi:pharmacy": ["Pharmacie (pharmacy)", "health"],
  "mdi:spa": ["Spa", "health"],
  "mdi:thermometer": ["Thermometer", "health"],
  "mdi:tooth": ["Tooth (tooth)", "health"],
  "mdi:wheelchair": ["Wheelchair", "health"],
  "mdi:car-emergency": ["Voiture emergency", "health"],
  "mdi:emergency-exit": ["Emergency exit", "health"],
  "mdi:home-thermometer": ["Maison thermometer", "health"],
  "mdi:hospital-box": ["Hôpital box", "health"],
  "mdi:hospital-location": ["Hôpital emplacement", "health"],
  "mdi:hospital-marker": ["Hôpital repère", "health"],
  "mdi:house-thermometer": ["Maison thermometer (house-thermometer)", "health"],
  "mdi:human-wheelchair": ["Personne wheelchair", "health"],
  "mdi:local-hospital": ["Local hôpital", "health"],
  "mdi:local-pharmacy": ["Local pharmacie", "health"],
  "mdi:medicine-bottle": ["Medicine bouteille", "health"],
  "mdi:mother-nurse": ["Mother nurse", "health"],
  "mdi:pill-bottle": ["Pill bouteille", "health"],
  "mdi:pill-multiple": ["Pill multiple", "health"],
  "mdi:pill-tablet": ["Pill tablet", "health"],
  "mdi:pool-thermometer": ["Piscine thermometer", "health"],
  "mdi:snowflake-thermometer": ["Neige thermometer", "health"],
  "mdi:sun-thermometer": ["Sun thermometer", "health"],
  "mdi:thermometer-add": ["Thermometer ajout", "health"],
  "mdi:thermometer-alert": ["Thermometer alerte", "health"],
  "mdi:thermometer-approve": ["Thermometer approve", "health"],
  "mdi:thermometer-auto": ["Thermometer automatique", "health"],
  "mdi:thermometer-bluetooth": ["Thermometer bluetooth", "health"],
  "mdi:thermometer-decrease": ["Thermometer decrease", "health"],
  "mdi:thermometer-high": ["Thermometer high", "health"],
  "mdi:thermometer-increase": ["Thermometer increase", "health"],
  "mdi:thermometer-lines": ["Thermometer lines", "health"],
  "mdi:thermometer-low": ["Thermometer low", "health"],
  "mdi:thermometer-probe": ["Thermometer probe", "health"],
  "mdi:thermometer-warning": ["Thermometer warning", "health"],
  "mdi:thermometer-water": ["Thermometer eau", "health"],
  "mdi:water-thermometer": ["Eau thermometer", "health"],
  "mdi:car-emergency-brake": ["Voiture emergency brake", "health"],
  "mdi:medical-cotton-swab": ["Médical cotton swab", "health"],
  "mdi:medicine-outline": ["Medicine contour", "health"],
  "mdi:spa-outline": ["Spa contour", "health"],
  "mdi:certificate": ["Certificate", "education"],
  "mdi:microscope": ["Microscope", "education"],
  "mdi:notebook": ["Notebook (notebook)", "education"],
  "mdi:pencil": ["Pencil", "education"],
  "mdi:teach": ["Teach", "education"],
  "mdi:university": ["Université (university)", "education"],
  "mdi:account-graduation": ["Personne graduation", "education"],
  "mdi:book-education": ["Livre education", "education"],
  "mdi:book-open": ["Livre ouvert", "education"],
  "mdi:bus-school": ["Bus école", "education"],
  "mdi:cast-school": ["Cast école", "education"],
  "mdi:chair-school": ["Chair école", "education"],
  "mdi:desk-lamp": ["Desk lamp", "education"],
  "mdi:graduation-cap": ["Graduation cap", "education"],
  "mdi:grease-pencil": ["Grease pencil", "education"],
  "mdi:lead-pencil": ["Lead pencil", "education"],
  "mdi:library-add": ["Bibliothèque ajout", "education"],
  "mdi:library-bookmark": ["Bibliothèque bookmark", "education"],
  "mdi:library-books": ["Bibliothèque books", "education"],
  "mdi:library-close": ["Bibliothèque close", "education"],
  "mdi:library-movie": ["Bibliothèque movie", "education"],
  "mdi:library-music": ["Bibliothèque music", "education"],
  "mdi:library-shelves": ["Bibliothèque shelves", "education"],
  "mdi:library-video": ["Bibliothèque vidéo", "education"],
  "mdi:local-library": ["Local bibliothèque", "education"],
  "mdi:notebook-favorite": ["Notebook favorite", "education"],
  "mdi:notebook-heart": ["Notebook heart", "education"],
  "mdi:notebook-love": ["Notebook love", "education"],
  "mdi:notebook-multiple": ["Notebook multiple", "education"],
  "mdi:cinema": ["Cinema (cinema)", "culture"],
  "mdi:movie": ["Movie", "culture"],
  "mdi:museum": ["Musée (museum)", "culture"],
  "mdi:palette": ["Palette", "culture"],
  "mdi:piano": ["Piano", "culture"],
  "mdi:theatre": ["Theatre (theatre)", "culture"],
  "mdi:account-music": ["Personne music", "culture"],
  "mdi:book-account": ["Livre personne", "culture"],
  "mdi:book-add": ["Livre ajout", "culture"],
  "mdi:book-alert": ["Livre alerte", "culture"],
  "mdi:book-alphabet": ["Livre alphabet", "culture"],
  "mdi:book-clock": ["Livre clock", "culture"],
  "mdi:book-cog": ["Livre cog", "culture"],
  "mdi:book-favorite": ["Livre favorite", "culture"],
  "mdi:book-location": ["Livre emplacement", "culture"],
  "mdi:book-lock": ["Livre verrou", "culture"],
  "mdi:book-love": ["Livre love", "culture"],
  "mdi:book-marker": ["Livre repère", "culture"],
  "mdi:book-multiple": ["Livre multiple", "culture"],
  "mdi:book-music": ["Livre music", "culture"],
  "mdi:book-play": ["Livre play", "culture"],
  "mdi:book-schedule": ["Livre schedule", "culture"],
  "mdi:book-search": ["Livre recherche", "culture"],
  "mdi:book-secure": ["Livre secure", "culture"],
  "mdi:book-time": ["Livre time", "culture"],
  "mdi:book-unsecure": ["Livre unsecure", "culture"],
  "mdi:book-variant": ["Livre variante", "culture"],
  "mdi:bookmark-music": ["Bookmark music", "culture"],
  "mdi:box-music": ["Box music", "culture"],
  "mdi:cheque-book": ["Cheque livre", "culture"],
  "mdi:dance-ballroom": ["Dance ballroom", "culture"],
  "mdi:dance-pole": ["Dance poteau", "culture"],
  "mdi:guitar-acoustic": ["Guitar acoustic", "culture"],
  "mdi:guitar-pick": ["Guitar pick", "culture"],
  "mdi:home-theater": ["Maison théâtre", "culture"],
  "mdi:home-theatre": ["Maison theatre (home-theatre)", "culture"],
  "mdi:microphone-add": ["Microphone ajout", "culture"],
  "mdi:microphone-help": ["Microphone help", "culture"],
  "mdi:microphone-message": ["Microphone message", "culture"],
  "mdi:microphone-question": ["Microphone question", "culture"],
  "mdi:bathtub": ["Bathtub (bathtub)", "accommodation"],
  "mdi:caravan": ["Caravan", "accommodation"],
  "mdi:home": ["Maison", "accommodation"],
  "mdi:house": ["Maison (house)", "accommodation"],
  "mdi:sofa": ["Sofa (sofa)", "accommodation"],
  "mdi:account-key": ["Personne clé", "accommodation"],
  "mdi:bed-clock": ["Lit clock", "accommodation"],
  "mdi:bed-double": ["Lit double", "accommodation"],
  "mdi:bed-empty": ["Lit empty", "accommodation"],
  "mdi:bed-king": ["Lit king", "accommodation"],
  "mdi:bed-queen": ["Lit queen", "accommodation"],
  "mdi:bed-schedule": ["Lit schedule", "accommodation"],
  "mdi:bed-single": ["Lit single", "accommodation"],
  "mdi:bed-time": ["Lit time", "accommodation"],
  "mdi:bunk-bed": ["Bunk lit", "accommodation"],
  "mdi:car-key": ["Voiture clé", "accommodation"],
  "mdi:cellphone-key": ["Cellphone clé", "accommodation"],
  "mdi:chart-home": ["Chart maison", "accommodation"],
  "mdi:cloud-key": ["Cloud clé", "accommodation"],
  "mdi:foreign-key": ["Foreign clé", "accommodation"],
  "mdi:green-house": ["Green maison", "accommodation"],
  "mdi:home-account": ["Maison personne", "accommodation"],
  "mdi:home-add": ["Maison ajout", "accommodation"],
  "mdi:home-alert": ["Maison alerte", "accommodation"],
  "mdi:home-analytics": ["Maison analytics", "accommodation"],
  "mdi:home-assistant": ["Maison assistant", "accommodation"],
  "mdi:home-attic": ["Maison attic", "accommodation"],
  "mdi:gondola": ["Gondola", "transport"],
  "mdi:scooter": ["Scooter", "transport"],
  "mdi:bus-alert": ["Bus alerte", "transport"],
  "mdi:bus-clock": ["Bus clock", "transport"],
  "mdi:bus-location": ["Bus emplacement", "transport"],
  "mdi:bus-marker": ["Bus repère", "transport"],
  "mdi:bus-multiple": ["Bus multiple", "transport"],
  "mdi:bus-side": ["Bus side", "transport"],
  "mdi:bus-sign": ["Bus sign", "transport"],
  "mdi:bus-warning": ["Bus warning", "transport"],
  "mdi:bus-wrench": ["Bus wrench", "transport"],
  "mdi:cable-car": ["Cable voiture", "transport"],
  "mdi:car-autonomous": ["Voiture autonomous", "transport"],
  "mdi:car-back": ["Voiture back", "transport"],
  "mdi:car-clock": ["Voiture clock", "transport"],
  "mdi:car-clutch": ["Voiture clutch", "transport"],
  "mdi:car-cog": ["Voiture cog", "transport"],
  "mdi:car-connected": ["Voiture connected", "transport"],
  "mdi:car-convertable": ["Voiture convertable", "transport"],
  "mdi:car-convertible": ["Voiture convertible", "transport"],
  "mdi:car-door": ["Voiture porte", "transport"],
  "mdi:car-esp": ["Voiture esp", "transport"],
  "mdi:car-estate": ["Voiture estate", "transport"],
  "mdi:car-find": ["Voiture find", "transport"],
  "mdi:car-handbrake": ["Voiture handbrake", "transport"],
  "mdi:car-hatchback": ["Voiture hatchback", "transport"],
  "mdi:car-horn": ["Voiture horn", "transport"],
  "mdi:car-info": ["Voiture info", "transport"],
  "mdi:car-insurance": ["Voiture insurance", "transport"],
  "mdi:car-limousine": ["Voiture limousine", "transport"],
  "mdi:car-location": ["Voiture emplacement", "transport"],
  "mdi:car-multiple": ["Voiture multiple", "transport"],
  "mdi:car-park": ["Voiture parc", "transport"],
  "mdi:car-pickup": ["Voiture pickup", "transport"],
  "mdi:car-police": ["Voiture police", "transport"],
  "mdi:car-rental": ["Voiture rental", "transport"],
  "mdi:car-repair": ["Voiture repair", "transport"],
  "mdi:car-saloon": ["Voiture saloon", "transport"],
  "mdi:car-search": ["Voiture recherche", "transport"],
  "mdi:car-seat": ["Voiture seat", "transport"],
  "mdi:car-select": ["Voiture select", "transport"],
  "mdi:car-side": ["Voiture side", "transport"],
  "mdi:car-smart": ["Voiture smart", "transport"],
  "mdi:car-sports": ["Voiture sports", "transport"],
  "mdi:car-suv": ["Voiture suv", "transport"],
  "mdi:car-turbocharger": ["Voiture turbocharger", "transport"],
  "mdi:car-wash": ["Voiture wash", "transport"],
  "mdi:car-windshield": ["Voiture windshield", "transport"],
  "mdi:car-wireless": ["Voiture wireless", "transport"],
  "mdi:car-wrench": ["Voiture wrench", "transport"],
  "mdi:directions-bus": ["Itinéraire bus", "transport"],
  "mdi:directions-car": ["Itinéraire voiture", "transport"],
  "mdi:directions-subway": ["Itinéraire métro", "transport"],
  "mdi:dump-truck": ["Dump camion", "transport"],
  "mdi:fire-truck": ["Incendie camion", "transport"],
  "mdi:fuel-truck": ["Carburant camion", "transport"],
  "mdi:hail-taxi": ["Hail taxi", "transport"],
  "mdi:hand-truck": ["Hand camion", "transport"],
  "mdi:human-scooter": ["Personne scooter", "transport"],
  "mdi:local-airport": ["Local aéroport", "transport"],
  "mdi:local-parking": ["Local parking", "transport"],
  "mdi:local-taxi": ["Local taxi", "transport"],
  "mdi:motorcycle-electric": ["Motorcycle electric", "transport"],
  "mdi:oil-truck": ["Pétrole camion", "transport"],
  "mdi:plane-car": ["Plane voiture", "transport"],
  "mdi:plane-train": ["Plane train", "transport"],
  "mdi:road-variant": ["Route variante", "transport"],
  "mdi:rv-truck": ["Rv camion", "transport"],
  "mdi:scooter-electric": ["Scooter electric", "transport"],
  "mdi:subway-variant": ["Métro variante", "transport"],
  "mdi:tanker-truck": ["Tanker camion", "transport"],
  "mdi:tow-truck": ["Tow camion", "transport"],
  "mdi:traffic-cone": ["Circulation cone", "transport"],
  "mdi:traffic-signal": ["Circulation signal", "transport"],
  "mdi:train-bus": ["Train bus", "transport"],
  "mdi:train-track": ["Train track", "transport"],
  "mdi:train-variant": ["Train variante", "transport"],
  "mdi:tram-side": ["Tramway side", "transport"],
  "mdi:truck-add": ["Camion ajout", "transport"],
  "mdi:truck-alert": ["Camion alerte", "transport"],
  "mdi:truck-delivery": ["Camion delivery", "transport"],
  "mdi:truck-error": ["Camion error", "transport"],
  "mdi:truck-fast": ["Camion fast", "transport"],
  "mdi:truck-flatbed": ["Camion flatbed", "transport"],
  "mdi:truck-freezer": ["Camion freezer", "transport"],
  "mdi:truck-pickup": ["Camion pickup", "transport"],
  "mdi:truck-refrigerator": ["Camion refrigerator", "transport"],
  "mdi:truck-shipping": ["Camion shipping", "transport"],
  "mdi:truck-snowflake": ["Camion neige", "transport"],
  "mdi:office": ["Bureau", "buildings"],
  "mdi:chess-castle": ["Chess château", "buildings"],
  "mdi:chess-tower": ["Chess tour", "buildings"],
  "mdi:desktop-tower": ["Desktop tour", "buildings"],
  "mdi:eiffel-tower": ["Eiffel tour", "buildings"],
  "mdi:garage-open": ["Garage ouvert", "buildings"],
  "mdi:garage-variant": ["Garage variante", "buildings"],
  "mdi:garage-warning": ["Garage warning", "buildings"],
  "mdi:home-bulb": ["Maison bulb", "buildings"],
  "mdi:home-chimney": ["Maison chimney", "buildings"],
  "mdi:home-electricity": ["Maison electricity", "buildings"],
  "mdi:home-energy": ["Maison energy", "buildings"],
  "mdi:home-find": ["Maison find", "buildings"],
  "mdi:home-flash": ["Maison flash", "buildings"],
  "mdi:home-lightbulb": ["Maison lightbulb", "buildings"],
  "mdi:home-location": ["Maison emplacement", "buildings"],
  "mdi:home-modern": ["Maison modern", "buildings"],
  "mdi:home-power": ["Maison énergie", "buildings"],
  "mdi:home-report": ["Maison report", "buildings"],
  "mdi:home-roof": ["Maison roof", "buildings"],
  "mdi:home-schedule": ["Maison schedule", "buildings"],
  "mdi:home-secure": ["Maison secure", "buildings"],
  "mdi:home-silo": ["Maison silo", "buildings"],
  "mdi:home-swap": ["Maison swap", "buildings"],
  "mdi:home-temperature": ["Maison température", "buildings"],
  "mdi:home-time": ["Maison time", "buildings"],
  "mdi:home-variant": ["Maison variante", "buildings"],
  "mdi:home-warning": ["Maison warning", "buildings"],
  "mdi:hoop-house": ["Hoop maison", "buildings"],
  "mdi:house-account": ["Maison personne", "buildings"],
  "mdi:house-attic": ["Maison attic", "buildings"],
  "mdi:house-bulb": ["Maison bulb (house-bulb)", "buildings"],
  "mdi:house-chimney": ["Maison chimney (house-chimney)", "buildings"],
  "mdi:house-city": ["Maison ville", "buildings"],
  "mdi:house-energy": ["Maison energy (house-energy)", "buildings"],
  "mdi:house-find": ["Maison find (house-find)", "buildings"],
  "mdi:house-flash": ["Maison flash (house-flash)", "buildings"],
  "mdi:house-group": ["Maison group", "buildings"],
  "mdi:house-heart": ["Maison heart", "buildings"],
  "mdi:house-lightbulb": ["Maison lightbulb (house-lightbulb)", "buildings"],
  "mdi:house-modern": ["Maison modern (house-modern)", "buildings"],
  "mdi:house-power": ["Maison énergie (house-power)", "buildings"],
  "mdi:house-roof": ["Maison roof (house-roof)", "buildings"],
  "mdi:house-schedule": ["Maison schedule (house-schedule)", "buildings"],
  "mdi:house-secure": ["Maison secure (house-secure)", "buildings"],
  "mdi:house-swap": ["Maison swap (house-swap)", "buildings"],
  "mdi:house-temperature": ["Maison température (house-temperature)", "buildings"],
  "mdi:house-time": ["Maison time (house-time)", "buildings"],
  "mdi:house-variant": ["Maison variante (house-variant)", "buildings"],
  "mdi:house-warning": ["Maison warning (house-warning)", "buildings"],
  "mdi:office-chair": ["Bureau chair", "buildings"],
  "mdi:radio-tower": ["Radio tour", "buildings"],
  "mdi:security-home": ["Sécurité maison", "buildings"],
  "mdi:shield-home": ["Protection maison", "buildings"],
  "mdi:shield-house": ["Protection maison (shield-house)", "buildings"],
  "mdi:smart-home": ["Smart maison", "buildings"],
  "mdi:smart-house": ["Smart maison (smart-house)", "buildings"],
  "mdi:alarm-arm-home": ["Alarm arm maison", "buildings"],
  "mdi:desktop-tower-monitor": ["Desktop tour monitor", "buildings"],
  "mdi:garage-open-variant": ["Garage ouvert variante", "buildings"],
  "mdi:cog": ["Cog", "industry"],
  "mdi:engine": ["Engine", "industry"],
  "mdi:hammer": ["Hammer", "industry"],
  "mdi:mine": ["Mine (mine)", "industry"],
  "mdi:wrench": ["Wrench", "industry"],
  "mdi:account-cog": ["Personne cog", "industry"],
  "mdi:account-wrench": ["Personne wrench", "industry"],
  "mdi:application-cog": ["Application cog", "industry"],
  "mdi:archive-cog": ["Archive cog", "industry"],
  "mdi:bell-cog": ["Bell cog", "industry"],
  "mdi:biscuit-cog": ["Biscuit cog", "industry"],
  "mdi:box-cog": ["Box cog", "industry"],
  "mdi:cellphone-cog": ["Cellphone cog", "industry"],
  "mdi:clapperboard-cog": ["Clapperboard cog", "industry"],
  "mdi:cloud-cog": ["Cloud cog", "industry"],
  "mdi:cog-box": ["Cog box", "industry"],
  "mdi:cog-clockwise": ["Cog clockwise", "industry"],
  "mdi:cog-counterclockwise": ["Cog counterclockwise", "industry"],
  "mdi:cog-pause": ["Cog pause", "industry"],
  "mdi:cog-play": ["Cog play", "industry"],
  "mdi:cog-stop": ["Cog stop", "industry"],
  "mdi:cog-transfer": ["Cog transfer", "industry"],
  "mdi:database-cog": ["Database cog", "industry"],
  "mdi:favorite-cog": ["Favorite cog", "industry"],
  "mdi:film-cog": ["Film cog", "industry"],
  "mdi:filter-cog": ["Filtre cog", "industry"],
  "mdi:fire-engine": ["Incendie engine", "industry"],
  "mdi:fuel-pump": ["Carburant pump", "industry"],
  "mdi:funnel-cog": ["Funnel cog", "industry"],
  "mdi:gantry-crane": ["Gantry crane", "industry"],
  "mdi:gas-pump": ["Gaz pump", "industry"],
  "mdi:hammer-screwdriver": ["Hammer screwdriver", "industry"],
  "mdi:hammer-sickle": ["Hammer sickle", "industry"],
  "mdi:hand-saw": ["Hand saw", "industry"],
  "mdi:head-cog": ["Head cog", "industry"],
  "mdi:heart-cog": ["Heart cog", "industry"],
  "mdi:heat-pump": ["Heat pump", "industry"],
  "mdi:iframe-cog": ["Iframe cog", "industry"],
  "mdi:jet-engine": ["Jet engine", "industry"],
  "mdi:message-cog": ["Message cog", "industry"],
  "mdi:monkey-wrench": ["Monkey wrench", "industry"],
  "mdi:movie-cog": ["Movie cog", "industry"],
  "mdi:petrol-pump": ["Petrol pump", "industry"],
  "mdi:pipe-disconnected": ["Pipe disconnected", "industry"],
  "mdi:pipe-leak": ["Pipe leak", "industry"],
  "mdi:pipe-valve": ["Pipe valve", "industry"],
  "mdi:pipe-wrench": ["Pipe wrench", "industry"],
  "mdi:progress-wrench": ["Progress wrench", "industry"],
  "mdi:slate-cog": ["Slate cog", "industry"],
  "mdi:smoking-pipe": ["Smoking pipe", "industry"],
  "mdi:star-cog": ["Étoile cog", "industry"],
  "mdi:store-cog": ["Magasin cog", "industry"],
  "mdi:table-cog": ["Table cog", "industry"],
  "mdi:thermostat-cog": ["Thermostat cog", "industry"],
  "mdi:timer-cog": ["Timer cog", "industry"],
  "mdi:construction": ["Construction", "infrastructure"],
  "mdi:network": ["Network", "infrastructure"],
  "mdi:satellite": ["Satellite", "infrastructure"],
  "mdi:server": ["Server", "infrastructure"],
  "mdi:account-network": ["Personne network", "infrastructure"],
  "mdi:add-network": ["Ajout network", "infrastructure"],
  "mdi:administrator-network": ["Administrator network", "infrastructure"],
  "mdi:clear-network": ["Clear network", "infrastructure"],
  "mdi:close-network": ["Close network", "infrastructure"],
  "mdi:console-network": ["Console network", "infrastructure"],
  "mdi:help-network": ["Help network", "infrastructure"],
  "mdi:ip-network": ["Ip network", "infrastructure"],
  "mdi:media-network": ["Media network", "infrastructure"],
  "mdi:multiply-network": ["Multiply network", "infrastructure"],
  "mdi:network-favorite": ["Network favorite", "infrastructure"],
  "mdi:network-favourite": ["Network favourite", "infrastructure"],
  "mdi:network-pos": ["Network pos", "infrastructure"],
  "mdi:network-router": ["Network router", "infrastructure"],
  "mdi:person-network": ["Person network", "infrastructure"],
  "mdi:play-network": ["Play network", "infrastructure"],
  "mdi:playstation-network": ["Playstation network", "infrastructure"],
  "mdi:question-network": ["Question network", "infrastructure"],
  "mdi:router-network": ["Router network", "infrastructure"],
  "mdi:satellite-uplink": ["Satellite uplink", "infrastructure"],
  "mdi:satellite-variant": ["Satellite variante", "infrastructure"],
  "mdi:security-network": ["Sécurité network", "infrastructure"],
  "mdi:server-add": ["Server ajout", "infrastructure"],
  "mdi:server-network": ["Server network", "infrastructure"],
  "mdi:server-security": ["Server sécurité", "infrastructure"],
  "mdi:server-shield": ["Server protection", "infrastructure"],
  "mdi:shield-network": ["Protection network", "infrastructure"],
  "mdi:table-network": ["Table network", "infrastructure"],
  "mdi:terminal-network": ["Terminal network", "infrastructure"],
  "mdi:tick-network": ["Tick network", "infrastructure"],
  "mdi:uac-network": ["Uac network", "infrastructure"],
  "mdi:user-network": ["User network", "infrastructure"],
  "mdi:access-point-network": ["Access point network", "infrastructure"],
  "mdi:android-debug-bridge": ["Android debug pont", "infrastructure"],
  "mdi:construction-outline": ["Construction contour", "infrastructure"],
  "mdi:fire-hydrant-alert": ["Incendie hydrant alerte", "infrastructure"],
  "mdi:local-area-network": ["Local zone network", "infrastructure"],
  "mdi:network-attached-storage": ["Network attached storage", "infrastructure"],
  "mdi:network-cash-box": ["Network cash box", "infrastructure"],
  "mdi:network-interface-card": ["Network interface card", "infrastructure"],
  "mdi:network-outline": ["Network contour", "infrastructure"],
  "mdi:bird": ["Bird", "nature"],
  "mdi:butterfly": ["Butterfly", "nature"],
  "mdi:earth": ["Earth", "nature"],
  "mdi:forest": ["Forêt (forest)", "nature"],
  "mdi:mushroom": ["Mushroom", "nature"],
  "mdi:earth-box": ["Earth box", "nature"],
  "mdi:flower-lotus": ["Fleur lotus", "nature"],
  "mdi:flower-pollen": ["Fleur pollen", "nature"],
  "mdi:flower-poppy": ["Fleur poppy", "nature"],
  "mdi:flower-tulip": ["Fleur tulipe", "nature"],
  "mdi:fly-flower": ["Fly fleur", "nature"],
  "mdi:island-variant": ["Île variante", "nature"],
  "mdi:leaf-circle": ["Feuille cercle", "nature"],
  "mdi:leaf-maple": ["Feuille maple", "nature"],
  "mdi:umbrella-beach": ["Umbrella plage", "nature"],
  "mdi:weather-cloudy": ["Weather cloudy", "nature"],
  "mdi:weather-date": ["Weather date", "nature"],
  "mdi:weather-drizzle": ["Weather drizzle", "nature"],
  "mdi:weather-dust": ["Weather dust", "nature"],
  "mdi:weather-flash": ["Weather flash", "nature"],
  "mdi:weather-fog": ["Weather fog", "nature"],
  "mdi:weather-hail": ["Weather hail", "nature"],
  "mdi:weather-hazy": ["Weather hazy", "nature"],
  "mdi:weather-history": ["Weather histoire", "nature"],
  "mdi:weather-hurricane": ["Weather hurricane", "nature"],
  "mdi:weather-mist": ["Weather brume", "nature"],
  "mdi:weather-night": ["Photographie nocturne", "nature"],
  "mdi:weather-partlycloudy": ["Weather partlycloudy", "nature"],
  "mdi:weather-pouring": ["Weather pouring", "nature"],
  "mdi:weather-sleet": ["Weather sleet", "nature"],
  "mdi:weather-snowy": ["Weather snowy", "nature"],
  "mdi:weather-spitting": ["Weather spitting", "nature"],
  "mdi:weather-storm": ["Weather storm", "nature"],
  "mdi:weather-sunset": ["Weather sunset", "nature"],
  "mdi:weather-thunder": ["Weather thunder", "nature"],
  "mdi:weather-time": ["Weather time", "nature"],
  "mdi:weather-tornado": ["Weather tornado", "nature"],
  "mdi:weather-windy": ["Weather windy", "nature"],
  "mdi:butterfly-outline": ["Butterfly contour", "nature"],
  "mdi:earth-arrow-down": ["Earth arrow down", "nature"],
  "mdi:earth-arrow-left": ["Earth arrow left", "nature"],
  "mdi:earth-arrow-right": ["Earth arrow right", "nature"],
  "mdi:earth-arrow-up": ["Earth arrow up", "nature"],
  "mdi:flower-outline": ["Fleur contour", "nature"],
  "mdi:forest-outline": ["Forêt contour", "nature"],
  "mdi:mushroom-outline": ["Mushroom contour", "nature"],
  "mdi:paw-outline": ["Paw contour", "nature"],
  "mdi:weather-cloudy-alert": ["Weather cloudy alerte", "nature"],
  "mdi:weather-cloudy-clock": ["Weather cloudy clock", "nature"],
  "mdi:weather-heavy-rain": ["Weather heavy rain", "nature"],
  "mdi:weather-lightning-rainy": ["Weather lightning rainy", "nature"],
  "mdi:weather-partly-cloudy": ["Weather partly cloudy", "nature"],
  "mdi:weather-partly-lightning": ["Weather partly lightning", "nature"],
  "mdi:weather-partly-rainy": ["Weather partly rainy", "nature"],
  "mdi:weather-partly-snowy": ["Weather partly snowy", "nature"],
  "mdi:weather-snowy-heavy": ["Weather snowy heavy", "nature"],
  "mdi:weather-snowy-rainy": ["Weather snowy rainy", "nature"],
  "mdi:weather-sun-wireless": ["Weather sun wireless", "nature"],
  "mdi:weather-sunny-alert": ["Weather sunny alerte", "nature"],
  "mdi:weather-sunset-down": ["Weather sunset down", "nature"],
  "mdi:weather-sunset-up": ["Weather sunset up", "nature"],
  "mdi:weather-thunder-rainy": ["Weather thunder rainy", "nature"],
  "mdi:weather-windy-variant": ["Weather windy variante", "nature"],
  "mdi:flower-lotus-outline": ["Fleur lotus contour", "nature"],
  "mdi:flower-pollen-outline": ["Fleur pollen contour", "nature"],
  "mdi:flower-tulip-outline": ["Fleur tulipe contour", "nature"],
  "mdi:leaf-circle-outline": ["Feuille cercle contour", "nature"],
  "mdi:umbrella-beach-outline": ["Umbrella plage contour", "nature"],
  "mdi:weather-cloudy-arrow-right": ["Weather cloudy arrow right", "nature"],
  "mdi:weather-hurricane-outline": ["Weather hurricane contour", "nature"],
  "mdi:weather-night-partly-cloudy": ["Weather night partly cloudy", "nature"],
  "mdi:weather-partly-snowy-rainy": ["Weather partly snowy rainy", "nature"],
  "mdi:pine-tree-multiple-outline": ["Pin arbre multiple contour", "nature"],
  "mdi:pine-tree-variant-outline": ["Pin arbre variante contour", "nature"],
  "mdi:weather-sun-wireless-outline": ["Weather sun wireless contour", "nature"],
  "mdi:cctv": ["Cctv", "access"],
  "mdi:fence": ["Fence", "access"],
  "mdi:ladder": ["Ladder", "access"],
  "mdi:warning": ["Warning", "access"],
  "mdi:account-alert": ["Personne alerte", "access"],
  "mdi:account-lock": ["Personne verrou", "access"],
  "mdi:account-warning": ["Personne warning", "access"],
  "mdi:add-alert": ["Ajout alerte", "access"],
  "mdi:alert-box": ["Alerte box", "access"],
  "mdi:alert-circle": ["Alerte cercle", "access"],
  "mdi:alert-decagram": ["Alerte decagram", "access"],
  "mdi:alert-octagon": ["Alerte octagon", "access"],
  "mdi:alert-octagram": ["Alerte octagram", "access"],
  "mdi:alert-rhombus": ["Alerte rhombus", "access"],
  "mdi:archive-alert": ["Archive alerte", "access"],
  "mdi:archive-lock": ["Archive verrou", "access"],
  "mdi:arm-barrier": ["Arm barrière", "access"],
  "mdi:attachment-lock": ["Attachment verrou", "access"],
  "mdi:automatic-gate": ["Automatic portail", "access"],
  "mdi:axis-lock": ["Axis verrou", "access"],
  "mdi:barrier-alert": ["Barrière alerte", "access"],
  "mdi:barrier-down": ["Barrière down", "access"],
  "mdi:barrier-up": ["Barrière up", "access"],
  "mdi:beaker-alert": ["Beaker alerte", "access"],
  "mdi:bell-alert": ["Bell alerte", "access"],
  "mdi:bell-warning": ["Bell warning", "access"],
  "mdi:biscuit-alert": ["Biscuit alerte", "access"],
  "mdi:biscuit-lock": ["Biscuit verrou", "access"],
  "mdi:blood-alert": ["Blood alerte", "access"],
  "mdi:boom-barrier": ["Boom barrière", "access"],
  "mdi:boom-gate": ["Boom portail", "access"],
  "mdi:box-alert": ["Box alerte", "access"],
  "mdi:box-lock": ["Box verrou", "access"],
  "mdi:calendar-alert": ["Calendar alerte", "access"],
  "mdi:calendar-lock": ["Calendar verrou", "access"],
  "mdi:calendar-warning": ["Calendar warning", "access"],
  "mdi:camera-lock": ["Appareil photo verrou", "access"],
  "mdi:caps-lock": ["Caps verrou", "access"],
  "mdi:cash-lock": ["Cash verrou", "access"],
  "mdi:cellphone-lock": ["Cellphone verrou", "access"],
  "mdi:chat-alert": ["Chat alerte", "access"],
  "mdi:chat-warning": ["Chat warning", "access"],
  "mdi:chili-alert": ["Piment alerte", "access"],
  "mdi:clock-alert": ["Clock alerte", "access"],
  "mdi:lamp": ["Lamp", "urban"],
  "mdi:park": ["Parc", "urban"],
  "mdi:sign": ["Sign", "urban"],
  "mdi:toilet": ["Toilet", "urban"],
  "mdi:trash": ["Trash", "urban"],
  "mdi:candelabra-lamp": ["Candelabra lamp", "urban"],
  "mdi:carriage-lamp": ["Carriage lamp", "urban"],
  "mdi:ceiling-lamp": ["Ceiling lamp", "urban"],
  "mdi:city-swap": ["Ville swap", "urban"],
  "mdi:city-switch": ["Ville switch", "urban"],
  "mdi:city-variant": ["Ville variante", "urban"],
  "mdi:coach-lamp": ["Coach lamp", "urban"],
  "mdi:contract-sign": ["Contract sign", "urban"],
  "mdi:currency-sign": ["Currency sign", "urban"],
  "mdi:document-sign": ["Document sign", "urban"],
  "mdi:elevator-down": ["Ascenseur down", "urban"],
  "mdi:elevator-up": ["Ascenseur up", "urban"],
  "mdi:floor-lamp": ["Floor lamp", "urban"],
  "mdi:fountain-pen": ["Fontaine pen", "urban"],
  "mdi:genie-lamp": ["Genie lamp", "urban"],
  "mdi:lava-lamp": ["Lava lamp", "urban"],
  "mdi:location-city": ["Emplacement ville", "urban"],
  "mdi:mailbox-open": ["Mailbox ouvert", "urban"],
  "mdi:mailbox-up": ["Mailbox up", "urban"],
  "mdi:markunread-mailbox": ["Markunread mailbox", "urban"],
  "mdi:oil-lamp": ["Pétrole lamp", "urban"],
  "mdi:outdoor-lamp": ["Outdoor lamp", "urban"],
  "mdi:post-lamp": ["Post lamp", "urban"],
  "mdi:recycle-variant": ["Recycle variante", "urban"],
  "mdi:sign-caution": ["Sign caution", "urban"],
  "mdi:sign-in": ["Sign in", "urban"],
  "mdi:sign-language": ["Sign language", "urban"],
  "mdi:sign-out": ["Sign out", "urban"],
  "mdi:sign-routes": ["Sign routes", "urban"],
  "mdi:sign-text": ["Sign text", "urban"],
  "mdi:sign-yield": ["Sign yield", "urban"],
  "mdi:stairs-box": ["Escaliers box", "urban"],
  "mdi:stairs-down": ["Escaliers down", "urban"],
  "mdi:stairs-up": ["Escaliers up", "urban"],
  "mdi:toilet-paper": ["Toilet paper", "urban"],
  "mdi:trash-can": ["Trash can", "urban"],
  "mdi:trash-circle": ["Trash cercle", "urban"],
  "mdi:trash-empty": ["Trash empty", "urban"],
  "mdi:trash-restore": ["Trash restore", "urban"],
  "mdi:trash-variant": ["Trash variante", "urban"],
  "mdi:water-recycle": ["Eau recycle", "urban"],
  "mdi:ceiling-lamp-multiple": ["Ceiling lamp multiple", "urban"],
  "mdi:atm": ["Atm", "commerce"],
  "mdi:briefcase": ["Briefcase", "commerce"],
  "mdi:cash": ["Cash", "commerce"],
  "mdi:mail": ["Mail", "commerce"],
  "mdi:mechanic": ["Mechanic", "commerce"],
  "mdi:scissors": ["Scissors", "commerce"],
  "mdi:shop": ["Commerce", "commerce"],
  "mdi:shopping": ["Courses", "commerce"],
  "mdi:account-cash": ["Personne cash", "commerce"],
  "mdi:bank-add": ["Banque ajout", "commerce"],
  "mdi:bank-circle": ["Banque cercle", "commerce"],
  "mdi:bank-transfer": ["Banque transfer", "commerce"],
  "mdi:briefcase-account": ["Briefcase personne", "commerce"],
  "mdi:briefcase-add": ["Briefcase ajout", "commerce"],
  "mdi:briefcase-clock": ["Briefcase clock", "commerce"],
  "mdi:briefcase-exchange": ["Briefcase exchange", "commerce"],
  "mdi:briefcase-eye": ["Briefcase eye", "commerce"],
  "mdi:briefcase-person": ["Briefcase person", "commerce"],
  "mdi:briefcase-search": ["Briefcase recherche", "commerce"],
  "mdi:briefcase-swap": ["Briefcase swap", "commerce"],
  "mdi:briefcase-tick": ["Briefcase tick", "commerce"],
  "mdi:briefcase-transfer": ["Briefcase transfer", "commerce"],
  "mdi:briefcase-user": ["Briefcase user", "commerce"],
  "mdi:briefcase-variant": ["Briefcase variante", "commerce"],
  "mdi:briefcase-view": ["Briefcase vue", "commerce"],
  "mdi:cart-add": ["Cart ajout", "commerce"],
  "mdi:cart-discount": ["Cart discount", "commerce"],
  "mdi:cart-favorite": ["Cart favorite", "commerce"],
  "mdi:cart-heart": ["Cart heart", "commerce"],
  "mdi:cart-percent": ["Cart percent", "commerce"],
  "mdi:cart-sale": ["Cart sale", "commerce"],
  "mdi:cart-variant": ["Cart variante", "commerce"],
  "mdi:cash-100": ["Cash 100", "commerce"],
  "mdi:cash-chargeback": ["Cash chargeback", "commerce"],
  "mdi:cash-clock": ["Cash clock", "commerce"],
  "mdi:cash-cycle": ["Cash cycle", "commerce"],
  "mdi:cash-fast": ["Cash fast", "commerce"],
  "mdi:cash-location": ["Cash emplacement", "commerce"],
  "mdi:cash-marker": ["Cash repère", "commerce"],
  "mdi:cash-multiple": ["Cash multiple", "commerce"],
  "mdi:cash-refund": ["Cash refund", "commerce"],
  "mdi:cash-return": ["Cash return", "commerce"],
  "mdi:cash-schedule": ["Cash schedule", "commerce"],
  "mdi:cash-usd": ["Cash usd", "commerce"],
  "mdi:cellphone-charging": ["Cellphone charging", "commerce"],
  "mdi:charging-station": ["Charging station", "commerce"],
  "mdi:contact-mail": ["Contact mail", "commerce"],
  "mdi:fuel-cell": ["Carburant cell", "commerce"],
  "mdi:fuel-station": ["Carburant station", "commerce"],
  "mdi:instant-cash": ["Instant cash", "commerce"],
  "mdi:local-atm": ["Local atm", "commerce"],
  "mdi:mail-certified": ["Mail certified", "commerce"],
  "mdi:vote": ["Vote", "administration"],
  "mdi:fire-station": ["Incendie station", "administration"],
  "mdi:passport-alert": ["Passport alerte", "administration"],
  "mdi:passport-biometric": ["Passport biometric", "administration"],
  "mdi:passport-electronic": ["Passport electronic", "administration"],
  "mdi:piggy-bank": ["Piggy banque", "administration"],
  "mdi:police-badge": ["Police badge", "administration"],
  "mdi:vote-recount": ["Vote recount", "administration"],
  "mdi:account-tie-hat": ["Personne tie hat", "administration"],
  "mdi:account-tie-voice": ["Personne tie voice", "administration"],
  "mdi:account-tie-woman": ["Personne tie woman", "administration"],
  "mdi:bank-transfer-in": ["Banque transfer in", "administration"],
  "mdi:bank-transfer-out": ["Banque transfer out", "administration"],
  "mdi:how-to-vote": ["How to vote", "administration"],
  "mdi:local-post-office": ["Local post bureau", "administration"],
  "mdi:office-building-cog": ["Bureau bâtiment cog", "administration"],
  "mdi:office-building-location": ["Bureau bâtiment emplacement", "administration"],
  "mdi:office-building-marker": ["Bureau bâtiment repère", "administration"],
  "mdi:shield-account-variant": ["Protection personne variante", "administration"],
  "mdi:vote-outline": ["Vote contour", "administration"],
  "mdi:where-to-vote": ["Where to vote", "administration"],
  "mdi:account-tie-outline": ["Personne tie contour", "administration"],
  "mdi:bank-circle-outline": ["Banque cercle contour", "administration"],
  "mdi:briefcase-account-outline": ["Briefcase personne contour", "administration"],
  "mdi:briefcase-add-outline": ["Briefcase ajout contour", "administration"],
  "mdi:briefcase-arrow-left-right": ["Briefcase arrow left right", "administration"],
  "mdi:briefcase-arrow-up-down": ["Briefcase arrow up down", "administration"],
  "mdi:clock": ["Clock (clock)", "heritage"],
  "mdi:account-clock": ["Personne clock", "heritage"],
  "mdi:alarm-clock": ["Alarm clock", "heritage"],
  "mdi:archive-clock": ["Archive clock", "heritage"],
  "mdi:biscuit-clock": ["Biscuit clock", "heritage"],
  "mdi:box-clock": ["Box clock", "heritage"],
  "mdi:calendar-clock": ["Calendar clock", "heritage"],
  "mdi:clock-arrow": ["Clock arrow", "heritage"],
  "mdi:clock-auto": ["Clock automatique", "heritage"],
  "mdi:clock-digital": ["Clock digital", "heritage"],
  "mdi:clock-end": ["Clock end", "heritage"],
  "mdi:clock-fast": ["Clock fast", "heritage"],
  "mdi:clock-in": ["Clock in", "heritage"],
  "mdi:clock-out": ["Clock out", "heritage"],
  "mdi:clock-start": ["Clock start", "heritage"],
  "mdi:clock-warning": ["Clock warning", "heritage"],
  "mdi:cloud-clock": ["Cloud clock", "heritage"],
  "mdi:database-clock": ["Database clock", "heritage"],
  "mdi:delete-clock": ["Delete clock", "heritage"],
  "mdi:event-clock": ["Event clock", "heritage"],
  "mdi:fan-clock": ["Fan clock", "heritage"],
  "mdi:home-clock": ["Maison clock", "heritage"],
  "mdi:house-clock": ["Maison clock (house-clock)", "heritage"],
  "mdi:invoice-clock": ["Invoice clock", "heritage"],
  "mdi:lock-clock": ["Verrou clock", "heritage"],
  "mdi:map-clock": ["Carte clock", "heritage"],
  "mdi:password-clock": ["Password clock", "heritage"],
  "mdi:payment-clock": ["Payment clock", "heritage"],
  "mdi:person-clock": ["Person clock", "heritage"],
  "mdi:phone-clock": ["Phone clock", "heritage"],
  "mdi:progress-clock": ["Progress clock", "heritage"],
  "mdi:receipt-clock": ["Receipt clock", "heritage"],
  "mdi:restore-clock": ["Restore clock", "heritage"],
  "mdi:routes-clock": ["Routes clock", "heritage"],
  "mdi:send-clock": ["Send clock", "heritage"],
  "mdi:shop-clock": ["Commerce clock", "heritage"],
  "mdi:store-clock": ["Magasin clock", "heritage"],
  "mdi:sun-clock": ["Sun clock", "heritage"],
  "mdi:table-clock": ["Table clock", "heritage"],
  "mdi:timeline-clock": ["Timeline clock", "heritage"],
  "mdi:tool-clock": ["Tool clock", "heritage"],
  "mdi:user-clock": ["User clock", "heritage"],
  "mdi:information": ["Information", "tourism"],
  "mdi:account-view": ["Personne vue", "tourism"],
  "mdi:archive-view": ["Archive vue", "tourism"],
  "mdi:box-view": ["Box vue", "tourism"],
  "mdi:cellphone-information": ["Cellphone information", "tourism"],
  "mdi:cellphone-map": ["Cellphone carte", "tourism"],
  "mdi:database-view": ["Database vue", "tourism"],
  "mdi:information-box": ["Information box", "tourism"],
  "mdi:information-circle": ["Information cercle", "tourism"],
  "mdi:information-symbol": ["Information symbol", "tourism"],
  "mdi:information-variant": ["Information variante", "tourism"],
  "mdi:local-attraction": ["Local attraction", "tourism"],
  "mdi:map-add": ["Carte ajout", "tourism"],
  "mdi:map-legend": ["Carte legend", "tourism"],
  "mdi:map-marker": ["Carte repère", "tourism"],
  "mdi:map-markers": ["Carte markers", "tourism"],
  "mdi:map-search": ["Carte recherche", "tourism"],
  "mdi:map-tick": ["Carte tick", "tourism"],
  "mdi:panorama-vr": ["Panorama vr", "tourism"],
  "mdi:printer-view": ["Printer vue", "tourism"],
  "mdi:smartphone-information": ["Smartphone information", "tourism"],
  "mdi:solar-compass": ["Solaire boussole", "tourism"],
  "mdi:sun-compass": ["Sun boussole", "tourism"],
  "mdi:table-picnic": ["Table pique-nique", "tourism"],
  "mdi:ticket-account": ["Ticket personne", "tourism"],
  "mdi:ticket-percent": ["Ticket percent", "tourism"],
  "mdi:ticket-user": ["Ticket user", "tourism"],
  "mdi:view-agenda": ["Vue agenda", "tourism"],
  "mdi:view-array": ["Vue array", "tourism"],
  "mdi:view-carousel": ["Vue carousel", "tourism"],
  "mdi:heart": ["Heart", "other"],
  "mdi:help": ["Help", "other"],
  "mdi:shape": ["Shape (shape)", "other"],
  "mdi:star": ["Étoile", "other"],
  "mdi:account-heart": ["Personne heart", "other"],
  "mdi:account-help": ["Personne help", "other"],
  "mdi:account-star": ["Personne étoile", "other"],
  "mdi:archive-star": ["Archive étoile", "other"],
  "mdi:box-star": ["Box étoile", "other"],
  "mdi:calendar-heart": ["Calendar heart", "other"],
  "mdi:calendar-help": ["Calendar help", "other"],
  "mdi:calendar-star": ["Calendar étoile", "other"],
  "mdi:chat-help": ["Chat help", "other"],
  "mdi:christmas-star": ["Christmas étoile", "other"],
  "mdi:clapperboard-star": ["Clapperboard étoile", "other"],
  "mdi:comment-help": ["Comment help", "other"],
} as const satisfies Readonly<Record<string, readonly [label: string, group: string]>>
