export type TripStatus = 'draft' | 'planned' | 'in_progress' | 'completed' | 'archived'
export type TripVisitStatus = 'planned' | 'visited' | 'skipped' | 'inaccessible' | 'postponed'
export type TripStopType = 'place' | 'free_location' | 'hotel' | 'restaurant' | 'parking' | 'station' | 'airport' | 'other'

export interface TripStop { id: string; trip_day_id: string; place_id: string | null; stop_type: TripStopType; name: string; latitude: number; longitude: number; address: string | null; sort_order: number; visit_duration_minutes: number | null; notes: string | null; is_required: boolean; is_locked: boolean; visit_status: TripVisitStatus }
export interface TripDay { id: string; trip_id: string; day_number: number; date: string | null; title: string | null; notes: string | null; planned_start_time: string | null; planned_end_time: string | null; max_total_duration_minutes: number | null; route_distance_meters: number | null; route_duration_seconds: number | null; visit_duration_minutes: number | null; total_duration_minutes: number | null; route_geometry: { type: 'LineString'; coordinates: [number, number][] } | null; route_segments: Array<{ distance_meters: number; duration_seconds: number; routable: boolean }> | null; route_status: string | null; sort_order: number; stops: TripStop[] }
export interface TripNight { id: string; trip_id: string; previous_day_id: string; next_day_id: string; place_id: string | null; name: string; latitude: number; longitude: number; address: string | null; notes: string | null; check_in_time: string | null; check_out_time: string | null }
export interface TripDeparture { id: string; trip_id: string; place_id: string | null; name: string; latitude: number; longitude: number; address: string | null; notes: string | null; departure_time: string | null }
export interface Trip { id: string; map_id: string; created_by_user_id: string; name: string; description: string | null; start_date: string | null; end_date: string | null; status: TripStatus; routing_profile: string; created_at: string; updated_at: string; completed_at: string | null; archived_at: string | null; days: TripDay[]; nights: TripNight[]; departure: TripDeparture | null }
export interface TripSummary { trip_id: string; days: number; nights: number; stops: number; unique_places: number; distance_meters: number; route_duration_seconds: number; visit_duration_minutes: number; total_duration_minutes: number; visit_status_counts: Record<string, number>; total_route_distance_meters: number; total_route_distance_km: number; total_route_duration_seconds: number; total_route_duration_minutes: number; total_visit_duration_minutes: number; total_pause_duration_minutes: number; total_buffer_duration_minutes: number; total_estimated_duration_minutes: number; days_with_route: number; days_without_route: number; stale_route_days: number; is_route_summary_complete: boolean }
export interface TripOptimization { manual_stop_ids: string[]; optimized_stop_ids: string[]; before: number; after: number; gain: number; metric: 'duration' | 'distance'; before_distance_meters: number; after_distance_meters: number; distance_gain_meters: number; before_duration_seconds: number; after_duration_seconds: number; duration_gain_seconds: number }
export interface TripExport { export_id: string; file_name: string; download_url: string; expires_at: string }
