from __future__ import annotations

from collections import defaultdict
from datetime import date, time
from html import escape
from io import BytesIO
from math import cos, radians
from pathlib import Path
from typing import Iterable
from urllib.parse import urlencode
from uuid import UUID

import qrcode
from PIL import Image as PillowImage
from reportlab.graphics.shapes import Circle, Drawing, Line, Path as DrawingPath, Rect, String
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFError, TTFont
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.countries.display_boundary import load_display_boundaries
from app.exports.temporary_exports import TemporaryExport, create
from app.photos.models import Photo
from app.photos.storage import PhotoStorageError, get_photo_thumbnail
from app.places.models import PlaceLink
from app.trips.models import Trip, TripDay
from app.trips.summary_service import day_summary, trip_summary


_TEXT = {
    "fr": {
        "booklet": "Carnet de voyage",
        "summary": "Résumé du voyage",
        "dates": "Dates",
        "days": "Jours",
        "stops": "Étapes",
        "distance": "Distance",
        "driving": "Conduite",
        "visits": "Visites",
        "total": "Durée totale",
        "overview": "Carte générale",
        "day": "Jour",
        "date": "Date",
        "recommended_start": "Départ recommandé",
        "estimated_arrival": "Arrivée estimée",
        "buffer": "Temps tampon",
        "margin": "Marge de sécurité",
        "accommodation": "Hébergement",
        "departure": "Départ",
        "arrival": "Arrivée",
        "poi": "Lieu",
        "photo": "Photo",
        "qr": "Itinéraire",
        "coordinates": "Coordonnées",
        "visit_duration": "Durée de visite",
        "schedule": "Chronologie",
        "not_available": "Non disponible",
        "no_photo": "Aucune photo",
        "generated": "Généré par CartaVault",
        "page": "Page",
        "route_missing": "Itinéraire non calculé ou à recalculer",
        "links": "Liens",
    },
    "en": {
        "booklet": "Travel booklet",
        "summary": "Trip summary",
        "dates": "Dates",
        "days": "Days",
        "stops": "Stops",
        "distance": "Distance",
        "driving": "Driving",
        "visits": "Visits",
        "total": "Total duration",
        "overview": "Overview map",
        "day": "Day",
        "date": "Date",
        "recommended_start": "Recommended start",
        "estimated_arrival": "Estimated arrival",
        "buffer": "Buffer time",
        "margin": "Safety margin",
        "accommodation": "Accommodation",
        "departure": "Departure",
        "arrival": "Arrival",
        "poi": "Place",
        "photo": "Photo",
        "qr": "Directions",
        "coordinates": "Coordinates",
        "visit_duration": "Visit duration",
        "schedule": "Timeline",
        "not_available": "Not available",
        "no_photo": "No photo",
        "generated": "Generated by CartaVault",
        "page": "Page",
        "route_missing": "Route missing or requires recalculation",
        "links": "Links",
    },
}

_MONTHS = {
    "fr": ("janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"),
    "en": ("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"),
}


def create_pdf(session: Session, trip: Trip, user_id: UUID, locale: str) -> TemporaryExport:
    language = locale if locale in _TEXT else "fr"
    item = create(trip.map_id, user_id, f"{_safe_name(trip.name)}.pdf")
    photos, links = _place_assets(session, trip)
    font, bold_font = _register_fonts()
    styles = _styles(font, bold_font)
    labels = _TEXT[language]
    summary = trip_summary(trip)

    document = SimpleDocTemplate(
        str(item.path),
        pagesize=A4,
        rightMargin=15 * mm,
        leftMargin=15 * mm,
        topMargin=15 * mm,
        bottomMargin=17 * mm,
        title=trip.name,
        author="CartaVault",
        subject=labels["booklet"],
    )
    story: list[object] = [
        Spacer(1, 18 * mm),
        Paragraph(escape(labels["booklet"]), styles["eyebrow"]),
        Paragraph(escape(trip.name), styles["cover_title"]),
    ]
    if trip.description:
        story.extend((Spacer(1, 4 * mm), Paragraph(_multiline(trip.description), styles["lead"])))
    story.extend((Spacer(1, 10 * mm), _summary_table(trip, summary, language, styles), PageBreak()))
    story.extend((Paragraph(escape(labels["overview"]), styles["h1"]), Spacer(1, 3 * mm), _overview_map(trip, language), Spacer(1, 5 * mm)))
    story.append(_summary_table(trip, summary, language, styles))

    for day in sorted(trip.days, key=lambda value: value.sort_order):
        story.append(PageBreak())
        story.extend(_day_section(trip, day, photos, links, language, styles))

    def decorate(canvas, _document) -> None:
        canvas.saveState()
        canvas.setTitle(trip.name)
        canvas.setAuthor("CartaVault")
        canvas.setFont(font, 8)
        canvas.setFillColor(colors.HexColor("#64748B"))
        canvas.drawString(15 * mm, 9 * mm, labels["generated"])
        canvas.drawRightString(A4[0] - 15 * mm, 9 * mm, f'{labels["page"]} {canvas.getPageNumber()}')
        canvas.restoreState()

    try:
        document.build(story, onFirstPage=decorate, onLaterPages=decorate)
    except Exception:
        item.path.unlink(missing_ok=True)
        raise
    return item


def _place_assets(session: Session, trip: Trip) -> tuple[dict[UUID, Photo], dict[UUID, list[PlaceLink]]]:
    place_ids = {stop.place_id for day in trip.days for stop in day.stops if stop.place_id is not None}
    if not place_ids:
        return {}, {}
    photo_rows = session.scalars(
        select(Photo)
        .where(Photo.place_id.in_(place_ids), Photo.path.is_not(None))
        .order_by(Photo.place_id, Photo.is_primary.desc(), Photo.sort_order, Photo.id)
    ).all()
    photos: dict[UUID, Photo] = {}
    for photo in photo_rows:
        if photo.place_id is not None:
            photos.setdefault(photo.place_id, photo)
    links: dict[UUID, list[PlaceLink]] = defaultdict(list)
    for link in session.scalars(
        select(PlaceLink).where(PlaceLink.place_id.in_(place_ids)).order_by(PlaceLink.place_id, PlaceLink.sort_order, PlaceLink.id)
    ).all():
        links[link.place_id].append(link)
    return photos, dict(links)


def _styles(font: str, bold_font: str) -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "body": ParagraphStyle("CVBody", parent=base["BodyText"], fontName=font, fontSize=9, leading=12, textColor=colors.HexColor("#334155")),
        "small": ParagraphStyle("CVSmall", parent=base["BodyText"], fontName=font, fontSize=7.5, leading=10, textColor=colors.HexColor("#475569")),
        "lead": ParagraphStyle("CVLead", parent=base["BodyText"], fontName=font, fontSize=11, leading=16, textColor=colors.HexColor("#475569"), alignment=TA_CENTER),
        "eyebrow": ParagraphStyle("CVEyebrow", parent=base["BodyText"], fontName=bold_font, fontSize=10, leading=12, textColor=colors.HexColor("#0F9F8B"), alignment=TA_CENTER, spaceAfter=4),
        "cover_title": ParagraphStyle("CVCover", parent=base["Title"], fontName=bold_font, fontSize=28, leading=34, textColor=colors.HexColor("#10213A"), alignment=TA_CENTER),
        "h1": ParagraphStyle("CVH1", parent=base["Heading1"], fontName=bold_font, fontSize=18, leading=22, textColor=colors.HexColor("#10213A"), spaceAfter=5),
        "h2": ParagraphStyle("CVH2", parent=base["Heading2"], fontName=bold_font, fontSize=12, leading=15, textColor=colors.HexColor("#10213A"), spaceBefore=6, spaceAfter=4),
        "table_header": ParagraphStyle("CVTableHeader", parent=base["BodyText"], fontName=bold_font, fontSize=8, leading=10, textColor=colors.white, alignment=TA_LEFT),
        "poi": ParagraphStyle("CVPoi", parent=base["BodyText"], fontName=bold_font, fontSize=9, leading=12, textColor=colors.HexColor("#10213A")),
    }


def _summary_table(trip: Trip, summary: dict, locale: str, styles: dict[str, ParagraphStyle]) -> Table:
    t = _TEXT[locale]
    date_value = _date_range(trip.start_date, trip.end_date, locale)
    values = (
        (t["dates"], date_value),
        (t["days"], str(summary["days"])),
        (t["stops"], str(summary["stops"])),
        (t["distance"], _distance(summary["total_route_distance_meters"], t)),
        (t["driving"], _duration(summary["total_route_duration_minutes"], t)),
        (t["total"], _duration(summary["total_planned_duration_minutes"], t)),
    )
    cells = [[Paragraph(escape(label), styles["small"]), Paragraph(escape(value), styles["poi"])] for label, value in values]
    table = Table(cells, colWidths=[35 * mm, 55 * mm], hAlign="CENTER", rowHeights=10 * mm)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
        ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#DDE5ED")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return table


def _day_section(
    trip: Trip,
    day: TripDay,
    photos: dict[UUID, Photo],
    links: dict[UUID, list[PlaceLink]],
    locale: str,
    styles: dict[str, ParagraphStyle],
) -> list[object]:
    t = _TEXT[locale]
    title = f'{t["day"]} {day.day_number}' + (f" - {day.title}" if day.title else "")
    elements: list[object] = [Paragraph(escape(title), styles["h1"])]
    if day.date:
        elements.append(Paragraph(f'<b>{escape(t["date"])}:</b> {escape(_format_date(day.date, locale))}', styles["body"]))
    if day.notes:
        elements.extend((Spacer(1, 2 * mm), Paragraph(_multiline(day.notes), styles["body"])))
    metrics = day_summary(day)
    elements.extend((Spacer(1, 4 * mm), _day_metrics(metrics, locale, styles)))
    if not metrics["has_current_route"]:
        elements.extend((Spacer(1, 2 * mm), Paragraph(escape(t["route_missing"]), styles["small"])))

    accommodation = next((night for night in trip.nights if night.previous_day_id == day.id), None)
    if accommodation:
        detail = escape(accommodation.name)
        if accommodation.address:
            detail += f" - {escape(accommodation.address)}"
        elements.extend((Spacer(1, 4 * mm), Paragraph(escape(t["accommodation"]), styles["h2"]), Paragraph(detail, styles["body"])))

    elements.extend((Spacer(1, 5 * mm), Paragraph(escape(t["schedule"]), styles["h2"])))
    rows: list[list[object]] = [[
        Paragraph("#", styles["table_header"]),
        Paragraph(escape(t["poi"]), styles["table_header"]),
        Paragraph(escape(t["photo"]), styles["table_header"]),
        Paragraph(escape(t["qr"]), styles["table_header"]),
    ]]
    entries: list[tuple[str, object, str | None]] = []
    if day.day_number == 1 and trip.departure is not None:
        entries.append(("D", trip.departure, t["departure"]))
    entries.extend((str(index), stop, None) for index, stop in enumerate(day.stops, 1))
    if day.day_number == len(trip.days) and trip.arrival is not None:
        entries.append(("A", trip.arrival, t["arrival"]))
    for order, stop, kind in entries:
        place_id = getattr(stop, "place_id", None)
        rows.append([
            Paragraph(order, styles["poi"]),
            _stop_description(stop, links.get(place_id, []) if place_id else [], locale, styles, kind),
            _photo(photos.get(place_id) if place_id else None, t, styles),
            _qr(_maps_url(stop)),
        ])
    if len(rows) == 1:
        rows.append(["", Paragraph(escape(t["not_available"]), styles["body"]), "", ""])
    table = Table(rows, colWidths=[10 * mm, 95 * mm, 43 * mm, 27 * mm], repeatRows=1, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(day.color or "#0FA68A")),
        ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#E2E8F0")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 1), (0, -1), "CENTER"),
        ("ALIGN", (2, 1), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 1), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
    ]))
    elements.append(table)
    return elements


def _day_metrics(summary: dict, locale: str, styles: dict[str, ParagraphStyle]) -> Table:
    t = _TEXT[locale]
    values = [
        (t["distance"], _distance(summary["route_distance_meters"], t)),
        (t["driving"], _duration(summary["route_duration_minutes"], t)),
        (t["visits"], _duration(summary["visit_duration_minutes"], t)),
        (t["buffer"], _duration(summary["buffer_duration_minutes"], t)),
        (t["margin"], _duration(summary["safety_margin_minutes"], t)),
        (t["recommended_start"], _clock(summary["recommended_start_time"], summary["recommended_start_day_offset"], t)),
        (t["estimated_arrival"], _clock(summary["estimated_arrival_time"], summary["estimated_arrival_day_offset"], t)),
        (t["total"], _duration(summary["total_duration_minutes"], t)),
    ]
    cells = []
    for index in range(0, len(values), 2):
        first, second = values[index], values[index + 1]
        cells.append([
            Paragraph(escape(first[0]), styles["small"]),
            Paragraph(escape(first[1]), styles["poi"]),
            Paragraph(escape(second[0]), styles["small"]),
            Paragraph(escape(second[1]), styles["poi"]),
        ])
    table = Table(cells, colWidths=[33 * mm, 52 * mm, 38 * mm, 52 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#DDE5ED")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return table


def _stop_description(stop: object, links: list[PlaceLink], locale: str, styles: dict[str, ParagraphStyle], kind: str | None = None) -> list[object]:
    t = _TEXT[locale]
    name = f"{kind}: {getattr(stop, 'name')}" if kind else str(getattr(stop, "name"))
    blocks: list[object] = [Paragraph(escape(name), styles["poi"])]
    details = []
    planned_time = getattr(stop, "planned_arrival", None) or getattr(stop, "departure_time", None)
    if planned_time:
        details.append(planned_time.strftime("%H:%M"))
    if hasattr(stop, "visit_duration_minutes"):
        details.append(f'{t["visit_duration"]}: {_duration(getattr(stop, "visit_duration_minutes"), t)}')
    if getattr(stop, "address", None):
        details.append(str(getattr(stop, "address")))
    details.append(f'{t["coordinates"]}: {getattr(stop, "latitude"):.5f}, {getattr(stop, "longitude"):.5f}')
    blocks.append(Paragraph("<br/>".join(escape(value) for value in details), styles["small"]))
    if links:
        rendered = " · ".join(
            f'<link href="{escape(link.url, quote=True)}">{escape(link.label or link.url)}</link>'
            for link in links[:4]
        )
        blocks.append(Paragraph(f'{escape(t["links"])}: {rendered}', styles["small"]))
    return blocks


def _photo(photo: Photo | None, labels: dict[str, str], styles: dict[str, ParagraphStyle]) -> object:
    if photo is None or photo.path is None or photo.place_id is None:
        return Paragraph(escape(labels["no_photo"]), styles["small"])
    try:
        path = get_photo_thumbnail(photo.path, photo.place_id, photo.id)
        with PillowImage.open(path) as source:
            width, height = source.size
        ratio = min((39 * mm) / width, (27 * mm) / height)
        return Image(str(path), width=width * ratio, height=height * ratio)
    except (PhotoStorageError, OSError, ValueError):
        return Paragraph(escape(labels["no_photo"]), styles["small"])


def _qr(url: str) -> Image:
    image = qrcode.make(url, border=1, box_size=4)
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    buffer.seek(0)
    return Image(buffer, width=20 * mm, height=20 * mm)


def _overview_map(trip: Trip, locale: str) -> Drawing:
    width, height = 175 * mm, 82 * mm
    drawing = Drawing(width, height)
    drawing.add(Rect(0, 0, width, height, rx=8, ry=8, fillColor=colors.HexColor("#F4F7F8"), strokeColor=colors.HexColor("#CBD5E1"), strokeWidth=0.6))
    points = _trip_points(trip)
    if not points:
        return drawing
    min_lon, max_lon, min_lat, max_lat = _map_bounds(points)
    mean_lat = (min_lat + max_lat) / 2
    longitude_scale = max(0.2, cos(radians(mean_lat)))

    def project(longitude: float, latitude: float) -> tuple[float, float]:
        x = 8 * mm + ((longitude - min_lon) * longitude_scale) / ((max_lon - min_lon) * longitude_scale) * (width - 16 * mm)
        y = 8 * mm + (latitude - min_lat) / (max_lat - min_lat) * (height - 16 * mm)
        return x, y

    country_code = getattr(getattr(trip.map, "country", None), "iso_alpha3", None)
    boundary = load_display_boundaries().get(country_code) if country_code else None
    if boundary:
        for polygon in boundary:
            for ring in polygon:
                path = DrawingPath()
                active = False
                for longitude, latitude in ring:
                    visible = min_lon <= longitude <= max_lon and min_lat <= latitude <= max_lat
                    if not visible:
                        active = False
                        continue
                    x, y = project(longitude, latitude)
                    if active:
                        path.lineTo(x, y)
                    else:
                        path.moveTo(x, y)
                        active = True
                path.strokeColor = colors.HexColor("#94A3B8")
                path.strokeWidth = 0.45
                path.fillColor = None
                drawing.add(path)

    for day in sorted(trip.days, key=lambda value: value.sort_order):
        route = (day.route_geometry or {}).get("coordinates") or [(stop.longitude, stop.latitude) for stop in day.stops]
        if len(route) >= 2:
            path = DrawingPath()
            for index, (longitude, latitude) in enumerate(route):
                x, y = project(float(longitude), float(latitude))
                (path.moveTo if index == 0 else path.lineTo)(x, y)
            path.strokeColor = colors.HexColor(day.color or "#0FA68A")
            path.strokeWidth = 2.2
            path.fillColor = None
            drawing.add(path)
        for stop in day.stops:
            x, y = project(stop.longitude, stop.latitude)
            color = colors.HexColor(day.color or "#0FA68A")
            drawing.add(Circle(x, y, 5, fillColor=color, strokeColor=colors.white, strokeWidth=1.2))
            drawing.add(String(x, y - 2.2, str(day.day_number), fontName="Helvetica-Bold", fontSize=6, textAnchor="middle", fillColor=colors.white))
    if boundary:
        _country_inset(drawing, boundary, points, width, height)
    label = "CartaVault - aperçu géographique local" if locale == "fr" else "CartaVault - local geographic overview"
    drawing.add(String(7 * mm, 4 * mm, label, fontName="CVSans", fontSize=6, fillColor=colors.HexColor("#64748B")))
    return drawing


def _country_inset(drawing: Drawing, boundary: list, points: list[tuple[float, float]], width: float, height: float) -> None:
    inset_width, inset_height = 39 * mm, 29 * mm
    origin_x, origin_y = width - inset_width - 5 * mm, 5 * mm
    drawing.add(Rect(origin_x, origin_y, inset_width, inset_height, rx=5, ry=5, fillColor=colors.white, fillOpacity=0.9, strokeColor=colors.HexColor("#CBD5E1"), strokeWidth=0.5))
    center_lon = sum(value[0] for value in points) / len(points)
    center_lat = sum(value[1] for value in points) / len(points)

    def polygon_distance(polygon: list) -> tuple[int, float]:
        values = [tuple(point) for ring in polygon for point in ring]
        min_lon, max_lon = min(value[0] for value in values), max(value[0] for value in values)
        min_lat, max_lat = min(value[1] for value in values), max(value[1] for value in values)
        contains = min_lon <= center_lon <= max_lon and min_lat <= center_lat <= max_lat
        delta_lon = 0 if min_lon <= center_lon <= max_lon else min(abs(center_lon - min_lon), abs(center_lon - max_lon))
        delta_lat = 0 if min_lat <= center_lat <= max_lat else min(abs(center_lat - min_lat), abs(center_lat - max_lat))
        return (0 if contains else 1, delta_lon * delta_lon + delta_lat * delta_lat)

    selected_polygon = min(boundary, key=polygon_distance)
    visible_boundary = [selected_polygon]
    country_points = [tuple(point) for polygon in visible_boundary for ring in polygon for point in ring]
    if not country_points:
        return
    country_min_lon = min(value[0] for value in country_points)
    country_max_lon = max(value[0] for value in country_points)
    country_min_lat = min(value[1] for value in country_points)
    country_max_lat = max(value[1] for value in country_points)
    longitude_scale = max(0.2, cos(radians((country_min_lat + country_max_lat) / 2)))
    country_width = max(0.01, (country_max_lon - country_min_lon) * longitude_scale)
    country_height = max(0.01, country_max_lat - country_min_lat)
    scale = min((inset_width - 6 * mm) / country_width, (inset_height - 6 * mm) / country_height)
    content_width = country_width * scale
    content_height = country_height * scale
    offset_x = origin_x + (inset_width - content_width) / 2
    offset_y = origin_y + (inset_height - content_height) / 2

    def project(longitude: float, latitude: float) -> tuple[float, float]:
        return (
            offset_x + (longitude - country_min_lon) * longitude_scale * scale,
            offset_y + (latitude - country_min_lat) * scale,
        )

    for polygon in visible_boundary:
        for ring in polygon:
            path = DrawingPath()
            for index, (longitude, latitude) in enumerate(ring):
                x, y = project(longitude, latitude)
                (path.moveTo if index == 0 else path.lineTo)(x, y)
            path.strokeColor = colors.HexColor("#64748B")
            path.strokeWidth = 0.35
            path.fillColor = colors.HexColor("#E2E8F0")
            drawing.add(path)
    marker_x, marker_y = project(center_lon, center_lat)
    drawing.add(Circle(marker_x, marker_y, 2.4, fillColor=colors.HexColor("#0FA68A"), strokeColor=colors.white, strokeWidth=0.7))


def _trip_points(trip: Trip) -> list[tuple[float, float]]:
    points: list[tuple[float, float]] = []
    for anchor in (trip.departure, trip.arrival):
        if anchor is not None:
            points.append((anchor.longitude, anchor.latitude))
    points.extend((night.longitude, night.latitude) for night in trip.nights)
    for day in trip.days:
        geometry = (day.route_geometry or {}).get("coordinates") or []
        points.extend((float(longitude), float(latitude)) for longitude, latitude in geometry)
        points.extend((stop.longitude, stop.latitude) for stop in day.stops)
    return points


def _map_bounds(points: Iterable[tuple[float, float]]) -> tuple[float, float, float, float]:
    values = list(points)
    longitudes = [value[0] for value in values]
    latitudes = [value[1] for value in values]
    min_lon, max_lon = min(longitudes), max(longitudes)
    min_lat, max_lat = min(latitudes), max(latitudes)
    lon_padding = max((max_lon - min_lon) * 0.12, 0.08)
    lat_padding = max((max_lat - min_lat) * 0.12, 0.08)
    return min_lon - lon_padding, max_lon + lon_padding, min_lat - lat_padding, max_lat + lat_padding


def _register_fonts() -> tuple[str, str]:
    regular_candidates = (
        Path("/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc"),
        Path("C:/Windows/Fonts/msyh.ttc"),
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
        Path("C:/Windows/Fonts/arial.ttf"),
        Path(__import__("reportlab").__file__).parent / "fonts" / "Vera.ttf",
    )
    bold_candidates = (
        Path("/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc"),
        Path("C:/Windows/Fonts/msyhbd.ttc"),
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"),
        Path("C:/Windows/Fonts/arialbd.ttf"),
        Path(__import__("reportlab").__file__).parent / "fonts" / "VeraBd.ttf",
    )
    _register_first_supported_font("CVSans", regular_candidates)
    _register_first_supported_font("CVSans-Bold", bold_candidates)
    return "CVSans", "CVSans-Bold"


def _register_first_supported_font(name: str, candidates: tuple[Path, ...]) -> None:
    if name in pdfmetrics.getRegisteredFontNames():
        return
    for path in candidates:
        if not path.is_file():
            continue
        try:
            pdfmetrics.registerFont(TTFont(name, str(path)))
            return
        except TTFError:
            continue
    raise RuntimeError("A supported Unicode TrueType font is required for PDF exports")


def _maps_url(stop: object) -> str:
    return "https://www.google.com/maps/search/?" + urlencode({"api": "1", "query": f"{getattr(stop, 'latitude')},{getattr(stop, 'longitude')}"})


def _safe_name(value: str) -> str:
    import re
    from unicodedata import normalize

    ascii_value = normalize("NFKD", value).encode("ascii", "ignore").decode("ascii").lower()
    return re.sub(r"[^a-z0-9]+", "-", ascii_value).strip("-")[:80] or "voyage"


def _date_range(start: date | None, end: date | None, locale: str) -> str:
    if start is None and end is None:
        return _TEXT[locale]["not_available"]
    if start == end or end is None:
        return _format_date(start, locale) if start else _format_date(end, locale)
    return f"{_format_date(start, locale)} - {_format_date(end, locale)}"


def _format_date(value: date | None, locale: str) -> str:
    if value is None:
        return _TEXT[locale]["not_available"]
    return f"{value.day} {_MONTHS[locale][value.month - 1]} {value.year}" if locale == "fr" else f"{_MONTHS[locale][value.month - 1]} {value.day}, {value.year}"


def _duration(minutes: int | float | None, labels: dict[str, str]) -> str:
    if minutes is None:
        return labels["not_available"]
    value = max(0, round(minutes))
    hours, remainder = divmod(value, 60)
    return f"{hours} h {remainder:02d}" if hours else f"{remainder} min"


def _distance(meters: int | float | None, labels: dict[str, str]) -> str:
    if meters is None:
        return labels["not_available"]
    return f"{float(meters) / 1000:.1f} km".replace(".", "," if labels is _TEXT["fr"] else ".")


def _clock(value: time | None, offset: int | None, labels: dict[str, str]) -> str:
    if value is None:
        return labels["not_available"]
    suffix = f" (+{offset} j)" if offset and labels is _TEXT["fr"] else f" (+{offset}d)" if offset else ""
    return value.strftime("%H:%M") + suffix


def _multiline(value: str) -> str:
    return escape(value).replace("\n", "<br/>")
